### ISSUE TITLE
Remove devincept points table and update the heading from "is" to "was"

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#104]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by khushi-purwar** [comment]
I want to work on this , please assign me.

**Comment by arpit456jain** [comment]
Go ahead @khushi-purwar
