### ISSUE TITLE
Quote Generator

### ISSUE THREAD

**Issue by khushi-purwar** [arpit456jain/Amazing-Js-Projects#106]
<b>Project Description</b>
This application will generate a random quote whenever user clicks on the button.

<b>Tech stacks Used</b>
- HTML
- CSS
- JS

**Comment by khushi-purwar** [comment]
I want to work on this issue, please assign me.

**Comment by arpit456jain** [comment]
@khushi-purwar you can ping me in discord server

**Comment by khushi-purwar** [comment]
> @khushi-purwar you can ping me in discord server

Ok
