### ISSUE TITLE
Color Checker

### ISSUE THREAD

**Issue by Sulagna-Dutta-Roy** [arpit456jain/Amazing-Js-Projects#107]
<h2>Project Description:</h2>
<p>The user can add any color and border color will change.This project is made by Javascript.</p>

<h4>Tech stacks used:</h4>
<ul>
  <li>Html5</li>
  <li>Css</li>
  <li>Javascript</li>
</ul>

**Comment by arpit456jain** [comment]
Go ahead @Sulagna-Dutta-Roy
