### ISSUE TITLE
I wish to make a ToDo list

### ISSUE THREAD

**Issue by ushmita4** [arpit456jain/Amazing-Js-Projects#11]
I wish to create a to do list.

**Comment by arpit456jain** [comment]
@ushmita4 although there is already a to do list present but no problem you can work on it just name it to do list type 2

**Comment by arpit456jain** [comment]
@ushmita4 any updates ?

**Comment by ushmita4** [comment]
Yes I am making it. Actually I was down with fever and had serious ache in my hand due to the vaccine.

**Comment by arpit456jain** [comment]
ok @ushmita4 take ur time

**Comment by arpit456jain** [comment]
@ushmita4 create a new issue when your PR is ready
