### ISSUE TITLE
minify css img is not rendering

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#113]
there is jpg file of minify css it should be png

**Comment by khushi-purwar** [comment]
> there is jpg file of minify css it should be png

Assign me this issue.

**Comment by arpit456jain** [comment]
ok @khushi-purwar 
and yeah add your calculator to json file also

**Comment by arpit456jain** [comment]
Then it will render here  automatically : https://amazing-js-projects.netlify.app/calculatorspage.html

**Comment by khushi-purwar** [comment]
> ok @khushi-purwar
> and yeah add your calculator to json file also

ok and the previous one also, i.e Quote generator?

**Comment by arpit456jain** [comment]
yes that also
