### ISSUE TITLE
add two more items in navbar and add these links

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#114]
cool front end templates : https://cool-front-end-templates.netlify.app/
amazing Css effects : https://amazing-css-effects.netlify.app/

**Comment by khushi-purwar** [comment]
> : https://amazing-css-effects.netlify.app/

Like this , we have to do?
![image](https://user-images.githubusercontent.com/52875298/129479665-414912b2-fe99-4d00-b7ba-b3b92156b3b1.png)

**Comment by arpit456jain** [comment]
> > : https://amazing-css-effects.netlify.app/
> 
> Like this , we have to do?
> ![image](https://user-images.githubusercontent.com/52875298/129479665-414912b2-fe99-4d00-b7ba-b3b92156b3b1.png)

yes yes @khushi-purwar make a PR for this

**Comment by khushi-purwar** [comment]
> > > : https://amazing-css-effects.netlify.app/
> > 
> > 
> > Like this , we have to do?
> > ![image](https://user-images.githubusercontent.com/52875298/129479665-414912b2-fe99-4d00-b7ba-b3b92156b3b1.png)
> 
> yes yes @khushi-purwar make a PR for this

OK.
