### ISSUE TITLE
Add remaining templates in style_link.json

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#12]
Add remaining templates in style_link.json and its url so that they can be accesed by home page

**Comment by shivaprasadyanala** [comment]
can u tell me how style_link.json work?

**Comment by arpit456jain** [comment]
`
{
    "name": "Calculator Type 1",
    "link": "Calculators/Calculator 1.html"
  },
`
add name of template and link of its main file it will automatically render it on home page

**Comment by Atif0604** [comment]
> `{ "name": "Calculator Type 1", "link": "Calculators/Calculator 1.html" },`
> add name of template and link of its main file it will automatically render it on home page

can i work on this @arpit456jain

**Comment by arpit456jain** [comment]
yes @Atif0604 go ahead
