### ISSUE TITLE
SuperHero Website

### ISSUE THREAD

**Issue by khushi-purwar** [arpit456jain/Amazing-Js-Projects#131]
**Features:**
1. Home page ->  a search bar  : User can search superhero from here, and result will be in the form of card
2. A single card should have superhero name basic details and poster and a view and addTofavourite button 
3. When user click on view details,  a superhero details page will open
4. addToFavorite button -> on click of it add super hero in favourite list 
5. favourite page -> show list of favourite super hero here ( with the help of local storage)
6. Remove favourite button and remove superhero from page on click .

**Comment by khushi-purwar** [comment]
Can I add this project for Hacktoberfest?

**Comment by arpit456jain** [comment]
yes sure
