### ISSUE TITLE
Delete .Ds_Store file

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#139]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Vikash-8090-Yadav** [comment]
hiii ..Greeting's of the day
I want to work on this issue under the GSSOC'22 ..
Plss assign this to me ...

**Comment by arpit456jain** [comment]
hey @Vikash-8090-Yadav please check read me also for grammatical errors

**Comment by Vikash-8090-Yadav** [comment]
Ok i will do :smile:

**Comment by Vikash-8090-Yadav** [comment]
> hey @Vikash-8090-Yadav please check read me also for grammatical errors

there's already issue gernated #164 

if u want i can also Chek ur readme file and update it ...

And i forget to mention that i am a contributor under 

### **GSSOC'22**
Thank's and regard's  :crossed_fingers:

**Comment by arpit456jain** [comment]
@astha2412 @VidhiBhatt01

**Comment by arpit456jain** [comment]
@Vikash-8090-Yadav please make a new pR after pulling the lastest changes and tag one of the mentors for review
