### ISSUE TITLE
Add Guess my number

### ISSUE THREAD

**Issue by abhi1e9-1e10** [arpit456jain/Amazing-Js-Projects#157]
In this project you have to guess a number, if your PREDICTED NUMBER is equal to the SECRET NUMBER you won!!! ♥
Key concepts covered :-
1.) document.querySelector()
2.) Math.random()
3.) eventListeners
4.) textContent
5.) Math.trunc()

**Comment by Rimjhim20** [comment]
Hey! @arpit456jain
I would like to work on this issue under GSSoC'22 .
Please Assign me with this issue .
Thank you in advance.

**Comment by anu-phoenix** [comment]
Can I work on this issue?
