### ISSUE TITLE
Add Roman Numeral Converter

### ISSUE THREAD

**Issue by abhi1e9-1e10** [arpit456jain/Amazing-Js-Projects#158]
The main objective of this project is to convert arabic numbers to Roman numerals or vice-versa.

Key concepts covered :-
1.) document.getElementById()
2.) event Listeners
3.) arabicToRoman()
4.) romanToArabic()
5.) objects
6.) for loop
7.) Math.floor()
8.) indexOf()
9.) replace()

**Comment by Rimjhim20** [comment]
Hey! @arpit456jain 
I would like to work on this issue under GSSoC'22  .
 Please Assign me with this issue .
 Thank you in advance.

**Comment by astha2412** [comment]
@abhi1e9-1e10 Make issue again when u r ready with your code!
