### ISSUE TITLE
Want to Add BMI Calculator

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [arpit456jain/Amazing-Js-Projects#159]
## Feature
* [x] Feature Request

## Describe the bug
This is not a bug. I want to add the BMI Calculator

## Screenshots
![Screenshot (675)](https://user-images.githubusercontent.com/73753957/156177907-ee2dbee9-5c34-4817-9d05-0f6cf122d983.png)
![Screenshot (676)](https://user-images.githubusercontent.com/73753957/156177936-bdae94c3-7b93-43c4-a6b6-b66bf2363608.png)
![Screenshot (677)](https://user-images.githubusercontent.com/73753957/156178034-cbbfed80-d612-4231-8a23-55b240f0450b.png)

**Comment by CoderSahil128** [comment]
Hello @arpit456jain.Hope you having a great time. I was just going through all the issues and found this one. I would love to work on this . I've built some numeric calculators by using glass morphism. So please assign this to me.

**Comment by gurjeetsinghvirdee** [comment]
@CoderSahil128 Bro, I made this issue It did not even exist before, You have to make your own issue or comment on Project Admin Created issues
