### ISSUE TITLE
Make a  responsive footer like this

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#161]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

Make a  responsive footer 
<img width="953" alt="footer" src="https://user-images.githubusercontent.com/55352601/156037848-2a69bc7a-212c-498f-8475-553cad539d75.png">

**Comment by Aditya-Harsh** [comment]
Hi there,
My name is Aditya Gupta. I am part GSSOC 2022 as a contributor and will be delighted work on this issue.
Therefore, I request you to assign me this issue.
Thanks.

**Comment by ShambhaviDixit09** [comment]
Hello,
My name is Shambhavi Dixit. I am part of GSSOC 2022 as a contributor and I can fix this issue.
Hence, I request you to assign me this work.
Thankyou.

**Comment by codervivek5** [comment]
I want to work on this issue under the Gssoc'22. plz assign me for the contribution. i will make it responsive for mobile compatable tablate compatable and also for desktop .......same to same screenshot

**Comment by astha2412** [comment]
First come first serve

**Comment by arpit456jain** [comment]
> I want to work on this issue under the Gssoc'22. plz assign me for the contribution. i will make it responsive for mobile compatable tablate compatable and also for desktop .......same to same screenshot

@codervivek5 u also start working on it

**Comment by codervivek5** [comment]
Thank you☺
