### ISSUE TITLE
Add weather app

### ISSUE THREAD

**Issue by AshutoshDash1999** [arpit456jain/Amazing-Js-Projects#162]
Hey, I want to add a weather app made by Tailwind CSS and JavaScript. 
Can you please assign this issue to me?

**Comment by AsmaIbrahimButt** [comment]
Im interested to work on this issue by using HTML 5,CSS3 ,Bootstrap And java script. Please assign me.

**Comment by Rimjhim20** [comment]
hey @arpit456jain 
I am gssoc'22 contributor
I want to work on this issue using html, CSS, JavaScript.
Please assign me with his issue.
Thank You!

**Comment by hrushi2003** [comment]
hey @astha2412 
i want to contribute to this project 
kindly assign me 
THANK YOU
