### ISSUE TITLE
To do list with Percentage

### ISSUE THREAD

**Issue by JyotiKM29** [arpit456jain/Amazing-Js-Projects#163]
# 
## Issue Type:

- [ ] Bug Report
- [X] Feature Request
- [ ] Documentaion

## **To-do list**

- Here we can add item in our list and check tick when done . It Shows how much work is done and left in Percentage view

## **ScreenShot**
 Similar like this
![image](https://user-images.githubusercontent.com/88364055/156146722-cd17631a-d553-44f1-956e-080bb994957f.png)

**Comment by AnIkeT126** [comment]
Can I work on this issue as a part of GSSoC'22?

**Comment by astha2412** [comment]
> Can I work on this issue as a part of GSSoC'22?

Make your own issue

**Comment by astha2412** [comment]
@JyotiKM29 Make a new issue when u r ready with your code and live link!
