### ISSUE TITLE
Improve README and check grammatical errors

### ISSUE THREAD

**Issue by shireenjain** [arpit456jain/Amazing-Js-Projects#164]
## Issue Type: 

I'm a contributor at GSSoC'22 and I'd like to enhance and proof read the contents of the Readme file since there is scope for the same. I'd like to take up this issue as well.

**Comment by lavakush07** [comment]
I am contributor at Gssoc 2022 can u assign this issue to me

**Comment by Avik-creator** [comment]
Could you pls assign this issue to me. I am an contributer to GSSOC22

**Comment by AshmitKesarwani** [comment]
I would like to take this , Can you Please assign me ?
I have made some logos before as well so I can contribute to it in a better way.

I am also a participant of GSSoC'22.
