### ISSUE TITLE
Add BMI Calculator

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [arpit456jain/Amazing-Js-Projects#166]
## Issue Type
* [x] Feature Request

## Describe the bug
This is not a bug. I want to add the BMI Calculator

## Screenshots
![Screenshot (677)](https://user-images.githubusercontent.com/73753957/156179767-1e7ed2d7-aa24-42ae-9091-b0d56abcb0da.png)
![Screenshot (675)](https://user-images.githubusercontent.com/73753957/156179789-9a80046c-577e-4e03-af0b-4dd9a2b7a57b.png)

**Comment by Avik-creator** [comment]
Hey there I would like to take this issue. So could you assign this to me. I am Avik Mukherjee GSSOC 22 participant

**Comment by anu-phoenix** [comment]
Can I work on this issue?

**Comment by gurjeetsinghvirdee** [comment]
> Can I work on this issue?

This issue PR was merged @anu-phoenix
