### ISSUE TITLE
Add 3D Photo Editor

### ISSUE THREAD

**Issue by gautamgc17** [arpit456jain/Amazing-Js-Projects#175]
## ADDING A 3D PHOTO EDITOR PROJECT
I want to add a 3D Photo Editor Project which will include features such as flipping the image horizontally or vertically, grayscale the image, rotate left or right and resizing. Please assign me this issue.

**Comment by mayank-del** [comment]
do the project closed??

**Comment by mayank-del** [comment]
Or i can contribute???

**Comment by astha2412** [comment]
> Or i can contribute???

Make your own issue
