### ISSUE TITLE
Add Random Quotes Generator 

### ISSUE THREAD

**Issue by gkumar-pandey** [arpit456jain/Amazing-Js-Projects#181]
## **Feature description**

- I want to add Random quotes generator javaScript project which can show random quotes after every click on a button.

**Comment by gkumar-pandey** [comment]
Hii @arpit456jain i want to add this project so, please assign to me for GSSoC22 . Thank you!

**Comment by Rimjhim20** [comment]
I want to ass random quote generator using html , css , javascript
 (
 document.getElementById(" ");
 const url = "https://api.quotable.io/random";
  fetch(url)
  .innerText ;
  .innerText ;                
 window.addEventListener ( );
 btn.addEventListener ( );
)

Please Assign me with this issue.
Thank you

**Comment by Pratyushpandey08** [comment]
Hi @arpit456jain I can add to this project , assign to me . I have also created random Jokes extension like this !!

**Comment by arpit456jain** [comment]
> Hi @arpit456jain I can add to this project , assign to me . I have also created random Jokes extension like this !!

sounds good create a new issue for this

**Comment by VidhiBhatt01** [comment]
@gkumar-pandey Someone else is also working on a similar project so name your folder as Quotes App 1 while raising PR

**Comment by astha2412** [comment]
@gkumar-pandey Make a new issue when u r ready with your code and live link!
