### ISSUE TITLE
Add Blury Loading 

### ISSUE THREAD

**Issue by gkumar-pandey** [arpit456jain/Amazing-Js-Projects#182]
## **Project description**

- Image is displayed with a blur filter over it.

**Comment by gkumar-pandey** [comment]
hello @arpit456jain i want to add this project so please assign to me.

**Comment by Rimjhim20** [comment]
hey! I want to  make Blurry Loading with html, CSS, and JavaScript( 
document.querySelector( ) ,
 document.innerHtml ,
blur  function( ) 
clearInterval( )
 )

Please assign me with this issue.

**Comment by arpit456jain** [comment]
@gkumar-pandey lets give her a chance
