### ISSUE TITLE
Website without footer. Umm Not so good.

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Amazing-Js-Projects#185]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

Sir assign this issue to me. I will start working on it, i am really passaionate about designig and development. 

## **Possible solution**

will add footer section 

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
something like this or any other design
![prrof1](https://user-images.githubusercontent.com/71981463/156302831-06ce0eba-d542-4c78-84a9-633497b4d4eb.JPG)

**Comment by Abh1shekSingh** [comment]
@arpit456jain  Please assign this iisue to me so that i can start working on it. I will definately create one beautiful footer for your website

**Comment by arpit456jain** [comment]
@Abh1shekSingh msg me on discord in dm
