### ISSUE TITLE
Add contributing guidlines.md

### ISSUE THREAD

**Issue by ankitapuri** [arpit456jain/Amazing-Js-Projects#19]
## Issue Type:
Create and Add contributing guidlines.md
[ ] Bug Report
[ ] Feature Request
[ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by rishabhrathore055** [comment]
@ankitapuri pls assign me this issue
