### ISSUE TITLE
Add a color guessing game

### ISSUE THREAD

**Issue by ManaliPawar** [arpit456jain/Amazing-Js-Projects#194]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Create a color guessing game wherein you have to guess the color from the RGB value that is generated every time we click on a new color. It has two levels easy and hard. The easy level contains three boxes (or options to guess) and the hard level contains 6 boxes. Once you select the right, all the boxes should change their color to the right color.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by mayank-del** [comment]
i am also a GSSoc 22 participant , can i work on this?
