### ISSUE TITLE
Add a random string generator 

### ISSUE THREAD

**Issue by BrownCoderAyush** [arpit456jain/Amazing-Js-Projects#200]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- It is not a bug, I want to add a notes maker app that I have made using Javascript.

## **Possible solution**

- you will see two types of random string generators:
     - Generate simple Random String
     - Generate Random alpha-numeric String

## **Screenshots**

-
 ![Screenshot (5)](https://user-images.githubusercontent.com/86606259/156366803-03f252af-6e37-4aba-9ab9-aa7d576b480a.png)

**Comment by BrownCoderAyush** [comment]
@arpit456jain Sir, can you assign this feature to me I have created a random string generator app for the same.

**Comment by omkar806** [comment]
@arpit456jain  Sir, can you assign this feature to me , I will create a random string generator with some designing to.
