### ISSUE TITLE
Creating logo for the website

### ISSUE THREAD

**Issue by DhairyaWankhade** [arpit456jain/Amazing-Js-Projects#203]

**Comment by anu-phoenix** [comment]
can I start working on this issue?

**Comment by AshmitKesarwani** [comment]
I would like to take this , Can you Please assign me ?
I have made some logos before as well so I can contribute to it in a better way.

I am also a participant of GSSoC'22.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by mayank-del** [comment]
I want to work on this under GSSOC2022. Can you assign it to me as well
.
