### ISSUE TITLE
Add a new project

### ISSUE THREAD

**Issue by Chirantanbanik** [arpit456jain/Amazing-Js-Projects#206]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

- It's not a bug, I want to add up a new project i.e. Random Joke Generator. 
Brief:
A static web page which is made with the help of HTML, CSS and Javascript. The jokes are generated with the help of an API call.

## **Screenshots/video**

https://user-images.githubusercontent.com/71392444/156394561-92c6dfbc-fd57-41b3-8e6b-07b5a7167085.mp4

**Comment by VidhiBhatt01** [comment]
Sure, go on!
