### ISSUE TITLE
i want to add Fresh New Quotes App 2

### ISSUE THREAD

**Issue by adi2002vicky** [arpit456jain/Amazing-Js-Projects#210]
![Screenshot 2022-03-02 214022](https://user-images.githubusercontent.com/78430607/156401460-46398d67-efbd-475a-9618-dc174f38055f.png)

**Comment by adi2002vicky** [comment]
pls assigned me sir #gssoc2022

**Comment by adi2002vicky** [comment]
please check pr sir i have my works

**Comment by VidhiBhatt01** [comment]
Someone else is also working on a similar idea so name your folder as Quotes App 2

**Comment by adi2002vicky** [comment]
@VidhiBhatt01 thankyou 
But second person folder name is:-
Add Random Quotes Generator

**Comment by VidhiBhatt01** [comment]
@adi2002vicky yes, he's naming the folder Quotes App 1 so yours will be Quotes App 2

**Comment by adi2002vicky** [comment]
Thankyou ma'am

**Comment by astha2412** [comment]
@adi2002vicky R u working on it???

**Comment by adi2002vicky** [comment]
> @adi2002vicky R u working on it???

no.....
