### ISSUE TITLE
Adding A Meme Generator

### ISSUE THREAD

**Issue by pragmatic-philosopher09** [arpit456jain/Amazing-Js-Projects#213]
## Issue Type:

- [x] Feature Request
- [x] Documentation

## **Describe the bug**

- New feature, not a bug.

## **Possible solution**

- Generate memes based on what images users upload and also the corresponding text, and also provide functionality for saving and downloading them.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

![images](https://user-images.githubusercontent.com/61372508/156405870-3f5eb993-d9e6-4340-875c-57149d30302f.jpg)

**Comment by pragmatic-philosopher09** [comment]
Can I work on this issue?

**Comment by VidhiBhatt01** [comment]
Assigned! Am excited for this, will be waiting for your PR : D

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022.

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903
