### ISSUE TITLE
Adding a Age Calculator

### ISSUE THREAD

**Issue by Rashmisingh-18** [arpit456jain/Amazing-Js-Projects#216]
Age Calculator using HTML, CSS and Javascript.

![🗓️ Age Calculator and 5 more pages - Personal - Microsoft​ Edge 02-03-2022 11 44 00 PM](https://user-images.githubusercontent.com/90052358/156423182-22fe2ebf-a705-4905-8e9f-78d896b51814.png)

![🗓️ Age Calculator and 5 more pages - Personal - Microsoft​ Edge 02-03-2022 11 44 15 PM](https://user-images.githubusercontent.com/90052358/156423057-65e1c1d9-d604-4836-bf25-60e649c21671.png)

**Comment by Rashmisingh-18** [comment]
Please assign this issue to me @arpit456jain

**Comment by sceary-expert** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

**Comment by Rashmisingh-18** [comment]
This issue is already solved and merged.
