### ISSUE TITLE
Guess the number game

### ISSUE THREAD

**Issue by Ravnoor12** [arpit456jain/Amazing-Js-Projects#221]
I am a contributor from GSSoc 2022. I want to add guess the number game, which will also tell the previous attempts and previous number of guesses.

**Comment by A-Spiral-Forge** [comment]
Please assign this to me @Ravnoor12

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by gopi-png** [comment]
I am a contributor from GSSoc 2022. I want to add guess the number game, which will also tell the previous attempts and previous number of guesses.

**Comment by gopi-png** [comment]
I want to work on this under GSSOC2022. Here is my discord profile Gopi Jambucha | Contributor#2262
