### ISSUE TITLE
Creating a  Real Time Chat App with HTML,CSS , Node js and socket.io

### ISSUE THREAD

**Issue by omkar806** [arpit456jain/Amazing-Js-Projects#234]
## Issue Type:

I want to add a new project , of a Real time chat web application , where I will  Design the interface of this application using HTML ,CSS and Javascript and also use Node Js and Socket.io for a real time chat based support to this application .

**Comment by omkar806** [comment]
@arpit456jain   can you please assign this issue to me , I will make a entire real time chat app with a good design and also real time chat feature .

**Comment by pawansharma197** [comment]
Hello Sir . I have completed this task and prepared a real time chat application with socket io with attractive UI . so plz assign this issue to me . I will make a pull request immediately .

**Comment by omkar806** [comment]
I was on the verge of completion this app. Why was my issue closed ? Please
I will create another issue ..please assign it to me
