### ISSUE TITLE
Will Create Calculator app with animation in pure HTML, CSS, Js

### ISSUE THREAD

**Issue by AdityaTheDev** [arpit456jain/Amazing-Js-Projects#238]
I'm a Gssoc22 contributor

**Comment by AdityaTheDev** [comment]
Should I start working on the project? Have you assigned?

**Comment by sceary-expert** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
