### ISSUE TITLE
Add Drum Kit

### ISSUE THREAD

**Issue by ri-tae-ka** [arpit456jain/Amazing-Js-Projects#24]
## Issue Type:
[ ] Feature Request

## **Describe the bug**
- I would like to add a Drum Kit project made using HTML, CSS and Javascript that would play sounds on keypresses as well as clicks.

Please assign me this issue.

**Comment by arpit456jain** [comment]
go ahead @ri-tae-ka

**Comment by arpit456jain** [comment]
@ri-tae-ka do not download or copy paste code from anywhere .
write your own code please

**Comment by arpit456jain** [comment]
@ri-tae-ka you want to work on it ?

**Comment by ri-tae-ka** [comment]
I have already completed the task.
Sorry I got confused if I needed to close the issue or it is the maintainer that should close the issue.

**Comment by arpit456jain** [comment]
ok no problem @ri-tae-ka
