### ISSUE TITLE
Will add a Mario Game made using Javascript and Kaboom.js

### ISSUE THREAD

**Issue by aroramrinaal** [arpit456jain/Amazing-Js-Projects#241]
**Project title**
Mario Game in **JavaScript** with **Kaboom.js**!.

**Project Description**
A game of Mario using JavaScript and Kaboom.js.

**Stack**:  
And in order to tick the check box just but x inside them for example - [x] like this. Please delete options that are not relevant.

- [x] Html
- [x] JavaScript
- [x] KaboomJS

## **Screenshots**

https://user-images.githubusercontent.com/90490253/156549075-5bb0560b-8c20-401e-9842-303e06e5fe26.mov

- If applicable, add screenshots to help explain your problem.

**Comment by aroramrinaal** [comment]
I am a GSSOC'22 Participant.

**Comment by astha2412** [comment]
@aroramrinaal Make a new issue when u r ready with your code and live link!
