### ISSUE TITLE
Add JavaScript Marvel Quiz

### ISSUE THREAD

**Issue by ProMinato500** [arpit456jain/Amazing-Js-Projects#243]
## **Project Description**

- A quiz game about Marvel Cinematic Universe using JavaScript, HTML, and CSS.

##Languages
- HTML
- CSS
- JavaScript

**Comment by ProMinato500** [comment]
@VidhiBhatt01 pls assign me this issue

**Comment by sceary-expert** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.

**Comment by mayank-del** [comment]
I  also WANT TO WORK ON THIS ISSUE UNDER GSSoC' 22.

**Comment by astha2412** [comment]
@ProMinato500 Make a new issue when u r ready with your code and live link!
