### ISSUE TITLE
Want to add a custom scroll bar for the website and also improve the navbar hover effect.

### ISSUE THREAD

**Issue by soumali28** [arpit456jain/Amazing-Js-Projects#248]
## Issue Type:

- [ ] Feature Request

## **Describe the bug**
I want to add a custom scroll bar to the website.

## **Possible solution**

This shall be done using html and css.

**Comment by VidhiBhatt01** [comment]
We have another issue where the person is working on the navbar hover effect. You can work on scroll bar.

**Comment by soumali28** [comment]
Ok sure.
