### ISSUE TITLE
Add a Music Player

### ISSUE THREAD

**Issue by rittikadeb** [arpit456jain/Amazing-Js-Projects#249]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [x] Documentaion

## **Description**

A music player with  features like play, pause, next and many more.

## **Stacks Used**

- HTML
- CSS
- Javascript

I am a GSSOC'22 contributor. Please assign this issue to me.

**Comment by mayank-del** [comment]
I am a gssoc 22 participant , please assign me also in this  work
