### ISSUE TITLE
Adding simple calculator

### ISSUE THREAD

**Issue by Debdeep1** [arpit456jain/Amazing-Js-Projects#251]
## Issue Type:

- [ x] Feature Request

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![img-2](https://user-images.githubusercontent.com/89895057/156592126-17e5b3e9-d9da-4437-b0ac-c3858c11b703.jpeg)

**Comment by Debdeep1** [comment]
I want to work on this issue under GSSoC'22

**Comment by VidhiBhatt01** [comment]
We already have multiple calculators
