### ISSUE TITLE
ball-game

### ISSUE THREAD

**Issue by Asttttha** [arpit456jain/Amazing-Js-Projects#252]
this a game that i have been working lately, there comes random holes, through which the ball is supposed to get passed, otherwise you lose.

i would like to make it look more professional, and later add some sound effects.
i've attached a snapshot of it below, and this is my project link. also, to count and display the highscore made by user in the game itself.

[(https://github.com/Asttttha/game)](https://asttttha.github.io/ball-game/)

please assign me.

![image_2022-03-03_204725](https://user-images.githubusercontent.com/95849912/156593965-4d48a96c-e798-43ee-9903-a75d1986ec76.png)

**Comment by VidhiBhatt01** [comment]
Sure!

**Comment by sceary-expert** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.
