### ISSUE TITLE
Add Spotify-Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [arpit456jain/Amazing-Js-Projects#257]
## Issue Type:
- [x] Feature Request

## **Describe the bug**

- Not a bug, want to add Spotify Clone

## **Screenshots**

![Screenshot (694)](https://user-images.githubusercontent.com/73753957/156626894-1230202d-f0c0-4c2e-8985-a114ff3b98fc.png)

**Comment by arpit456jain** [comment]
it will work also
 playing songs ?

**Comment by gurjeetsinghvirdee** [comment]
> it will work also playing songs ?

for premium users
