### ISSUE TITLE
Memory Game in JS

### ISSUE THREAD

**Issue by kiruba-r11** [arpit456jain/Amazing-Js-Projects#26]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

- Add a memory game. It is a 4 * 4 grid-based game, and you have to remember the last food tile🍔 you clicked on. 
- Features:
  - It is responsive
  - It is sound effects for the correct and wrong match, and for game end.
  - It also has a live score feature, which updates after every move is made.

**Comment by kiruba-r11** [comment]
@arpit456jain @ankitapuri I would like to work on this as a part of DCP'21

**Comment by ankitapuri** [comment]
Go ahead @kiruba-r11
