### ISSUE TITLE
add a bootstrap cdn link properly

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#264]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Abh1shekSingh** [comment]
Hi @arpit456jain  please Assign this issue to me... I can handle this issue really easily, I already fix this issue on your Amazing CSS effect Project... And can fix in this project also

**Comment by Abh1shekSingh** [comment]
**RESOLVED SUCCESSFULLY ! WAITING FOR ASSIGNMENT**
![everything ok](https://user-images.githubusercontent.com/71981463/156694286-35b85cd9-f79e-483a-9ec6-c827cbd173c3.JPG)
![cdn](https://user-images.githubusercontent.com/71981463/156694281-a053efa5-bbad-4aea-a893-dd505eea17cd.JPG)
