### ISSUE TITLE
Currency Convertor

### ISSUE THREAD

**Issue by priyanshi1282** [arpit456jain/Amazing-Js-Projects#265]
## Add a new feature (Currency Convertor)
This convertor has more than 30 currencies option to convert, hence it will help a wide range of people.
<i>I'm willing to add this feature, so please assign this issue to me under <b>GSSoC'22 Contribution</b></i>. 

## **Screenshots**
![Screenshot (72)](https://user-images.githubusercontent.com/88632352/156645415-a999683e-7eab-4556-a19e-9990cb97016b.png)

**Comment by sceary-expert** [comment]
I want to work on this under GSSOC2022. Here is my discord profile DHANANJOY DEY | Contributor#7903

**Comment by priyanshi1282** [comment]
hey @arpit456jain , I have raised my PR. Please do review once 😃.
