### ISSUE TITLE
BaseX Converter

### ISSUE THREAD

**Issue by XZANATOL** [arpit456jain/Amazing-Js-Projects#268]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

Add a base-X to Base-Y converter that allows to convert from and to desired bases depending on user input. Example:
* From Decimal to Binary
* From Octal to Hexadecimal
* From Base-3 to Base-6

## **Possible solution**

- The web page will make use of HTML,CSS & JS

Issue made under GSSoC'22 contributions

**Comment by 13-Joban** [comment]
i want to work on this please assign me this project @VidhiBhatt01

**Comment by VidhiBhatt01** [comment]
@13-Joban issues are assigned on a first come first serve basis. You can check out the repo and find bugs as well as create new issues on your own as well
