### ISSUE TITLE
Add Image Resizer App

### ISSUE THREAD

**Issue by itaintkevin** [arpit456jain/Amazing-Js-Projects#274]
## Description

Hey! Arpit,
I would like to make an Image Resizer App.
- User can upload images of any ratio.
- Resize them with or without maintaining the aspect ratio.
- And just click to download.

I am a GSSoC22 participant, and would like to work on this project and contribute to this repository!
Please assign this project to me!

**Comment by itaintkevin** [comment]
@arpit456jain Can you assign this issue to me.

**Comment by Abhilasha-Jairath** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.
