### ISSUE TITLE
Add a spotify clone 

### ISSUE THREAD

**Issue by ManaliPawar** [arpit456jain/Amazing-Js-Projects#277]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by ManaliPawar** [comment]
Please assign me this issue

**Comment by pawansharma197** [comment]
Hello Sir . Plz assign this issue to me as I have  almost completed This project and I can make a pull within 2 day after assigning it to me .

**Comment by gopi-png** [comment]
I had be glad to contribute on this issue.

**Comment by mayank-del** [comment]
please assign me also in this issue, i will love to contribute in this issue
