### ISSUE TITLE
Add  Payment-Page  with  HTML,  CSS  and  JS

### ISSUE THREAD

**Issue by darkhorse-2000** [arpit456jain/Amazing-Js-Projects#278]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [x] Documentaion

## **Description**

- A payment page using frontend.

## **Stacks Used**

- HTML
- CSS
- Javascript

I am a GSSOC'22 Contributor. Please assign this issue to me.

**Comment by ShambhaviKool** [comment]
Hi.
I  am GSSoC '22 contributor and I can work on this issue please assign it.

**Comment by VidhiBhatt01** [comment]
@darkhorse-2000 I have assigned the issue as of now but if your project consists of very less JS, please close this issue here and raise it in cool frontend templates repo.

**Comment by darkhorse-2000** [comment]
In my project JS code is very less so I am closing this issue and raising it in cool frontend templates repo.
