### ISSUE TITLE
Add Random shapes and Backgrounds

### ISSUE THREAD

**Issue by mansi-singla-31215** [arpit456jain/Amazing-Js-Projects#284]
## **Project Description**
A project in which we can change the body background and shape of the objects with the help of buttons.

## Screenshot
<img width="959" alt="image" src="https://user-images.githubusercontent.com/83231180/156786641-40bc3534-7af9-4a9a-acb3-1f0858789b4b.png">

## Languages Used
 -HTML
 -CSS
 -JS

**Comment by mansi-singla-31215** [comment]
I am a GSSOC'22 contributor. Please assign this issue to me.

**Comment by shahishree03** [comment]
Please assigned to me this as GSSOC 22 contributior
