### ISSUE TITLE
Add a Color Code Converter

### ISSUE THREAD

**Issue by XZANATOL** [arpit456jain/Amazing-Js-Projects#288]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

Add a color code converter that can change code formats between RGB, Hex, CMYK, & Hsl.

## **Possible solution**

Going to make use of HTML, CSS, & JS.

## **Screenshots**

![Capture](https://user-images.githubusercontent.com/64689436/156847898-7da231eb-c578-417e-be9f-4bf023302529.PNG)

**Comment by mayank-del** [comment]
hello is there any issue with birthday countdown?, why it is not working properly?
