### ISSUE TITLE
Styling Navigation Bar for Calculators Page

### ISSUE THREAD

**Issue by sarthakdelori** [arpit456jain/Amazing-Js-Projects#293]
## Issue Type:

- [x] Bug Report

## **Describe the bug**

- The navbar is not styled for the Calculators page. 

## **Possible solution**

- I will style it according as the other pages.

## **Screenshots**

![image](https://user-images.githubusercontent.com/70380794/156875480-c0426b81-3f56-42a2-9f2c-b7c4c789aadd.png)

**Comment by arpit456jain** [comment]
its solved
