### ISSUE TITLE
Ping ball game score keeper

### ISSUE THREAD

**Issue by yellowberard** [arpit456jain/Amazing-Js-Projects#294]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Ping Pong Ball Score Keeper **

- A website where a user can keep score for their game and restart the game again.
## **Screenshots**
<image src="https://user-images.githubusercontent.com/82977727/124570137-39a2d280-de64-11eb-852d-8281d6149c58.png"> Counting Scores </image>

**Comment by mayank-del** [comment]
I WANT TO WORK ON THIS ISSUE UNDER GSSOC'22.
