### ISSUE TITLE
Dice Game

### ISSUE THREAD

**Issue by dsasaank-369** [arpit456jain/Amazing-Js-Projects#313]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**
-It is not a bug. I want to add a game. It is a fun game that helps to decide a player to win.

**Comment by mayank-del** [comment]
can i work on it under GSSoC' 22, please assign me  this work

**Comment by VidhiBhatt01** [comment]
@mayank-del issues are assigned on FCFS basis. You can check out other issues/find bugs/create issues on your own
