### ISSUE TITLE
add points Table in Readme

### ISSUE THREAD

**Issue by rishabhrathore055** [arpit456jain/Amazing-Js-Projects#32]
## Issue Type:

[ ] Bug Report
[ ] Feature Request
[x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/77366500/125955840-ac0a2b4c-3bba-4eb0-8905-e151a300da89.png)

**Comment by arpit456jain** [comment]
Ok sure @rishabhrathore055

**Comment by rishabhrathore055** [comment]
@arpit456jain check it once 
![image](https://user-images.githubusercontent.com/77366500/125959000-b0d4e1cb-6ada-40cc-af74-ea40a80ed466.png)
