### ISSUE TITLE
Background color changer

### ISSUE THREAD

**Issue by mayank-del** [arpit456jain/Amazing-Js-Projects#323]
## Issue Type:

- [ ] Bug Report
- [y ] Feature Request
- [ ] Documentaion

## **Describe the bug**

-There is not any bug, i want enhance the UI . It is looking like old website, colors can be enhanced. Just see the screenshot, i can enhance it and make it much better.

## **Possible solution**

- I will add mix colors or different background ,so, that it will look very nice,

## **Screenshots**

- 
![Screenshot 2022-03-07 123723](https://user-images.githubusercontent.com/82238106/156984225-b9a894f3-877d-4bad-aa9a-195cd79c3161.png)

**Comment by mayank-del** [comment]
Please assign me this issue under GSSoC, 22

**Comment by VidhiBhatt01** [comment]
Go on! Do enter before and after images in the PR description.
