### ISSUE TITLE
Better Card Components i.e. Cards UI UX

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Amazing-Js-Projects#324]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

These Cards UI doesn't look good, I want to make better UI for Cards

**Comment by Abh1shekSingh** [comment]
@arpit456jain  PLEASE ASSIGN THIS TO ME

**Comment by ronitrangwani** [comment]
I want to work on this under GSSOC2022. Can you assign it to me.

**Comment by VidhiBhatt01** [comment]
> @Abh1shekSingh please include some SS or video

@Abh1shekSingh

**Comment by arpit456jain** [comment]
Go ahead @Abh1shekSingh and do all the things i had mentioned you in dm
