### ISSUE TITLE
Login-Signup Page

### ISSUE THREAD

**Issue by sirilalithaadapa** [arpit456jain/Amazing-Js-Projects#330]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Creation of a Login-Signup Page.
## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![Screenshot2](https://user-images.githubusercontent.com/70501362/157089131-5dbd44a6-56f6-43ea-93ca-3365cd478aa6.png)

**Comment by arpit456jain** [comment]
@sirilalithaadapa this  is project is only for js projects
