### ISSUE TITLE
Real time chat application using ReactJS

### ISSUE THREAD

**Issue by Shubhayu-Bhowmick** [arpit456jain/Amazing-Js-Projects#344]
## Issue Type:

- [ ] Bug Report
- [X] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Creating a real time chat application using ReactJS.

## **Possible solution**

- Using Html, Css, Javascript, ReactJS, Chat Engine.

## **Screenshots**

- 
![chatapp](https://user-images.githubusercontent.com/69085132/157407097-61681b7a-8f36-4788-83db-7504b4f319d4.png)

**Comment by VidhiBhatt01** [comment]
As of now, we are only including Vanilla JS projects in this repo
