### ISSUE TITLE
Add a FlipBook

### ISSUE THREAD

**Issue by shivam123-dev** [arpit456jain/Amazing-Js-Projects#347]
I am a GSSOC'22 participant and want to add a flipbook project which is made using HTML, CSS and JS 

### Screenshots

![image](https://user-images.githubusercontent.com/81038095/157507417-a710c60b-748e-40fe-8e33-9840e824291e.png)
![image](https://user-images.githubusercontent.com/81038095/157507470-62bd7c21-da22-42d3-9204-a4fe79683271.png)

@VidhiBhatt01 Kindly assign me this issue

**Comment by VidhiBhatt01** [comment]
Go on , please try to make it responsive if possible.

**Comment by shivam123-dev** [comment]
@VidhiBhatt01 Please review my PR
