### ISSUE TITLE
Add a Pokemon Generator

### ISSUE THREAD

**Issue by Adit0507** [arpit456jain/Amazing-Js-Projects#348]
## Issue Type:

- [x] Feature Request

## **Describe the feature**

- I wish to add a Pokemon Generator which uses free Pokemon API.
- Live site: https://adit0507.github.io/Pokemon-Card-Generator/

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![Pokemon](https://user-images.githubusercontent.com/78037846/157664575-4e8a85bf-56f5-4185-8493-bcdbfedc34c0.PNG)

**Comment by VidhiBhatt01** [comment]
This is cool !!
