### ISSUE TITLE
Want to add Google Search Engine Clone

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [arpit456jain/Amazing-Js-Projects#350]
## Issue Type:
- [x] Feature Request

## **Describe the bug**

- This was not a bug, I want to add Google Search Engine Clone

## **Screenshots**

![Screenshot (696)](https://user-images.githubusercontent.com/73753957/157684445-f95106d1-a225-4238-bfe4-f336ad4bba38.png)
![Screenshot (697)](https://user-images.githubusercontent.com/73753957/157684470-1ba201f4-4ae4-44f7-9760-4ec2d2871cff.png)

**Comment by VidhiBhatt01** [comment]
@gurjeetsinghvirdee did you raise this issue in some other repo as well?

**Comment by gurjeetsinghvirdee** [comment]
> @gurjeetsinghvirdee did you raise this issue in some other repo as well?

In Ace the front end

**Comment by VidhiBhatt01** [comment]
> > @gurjeetsinghvirdee did you raise this issue in some other repo as well?
> 
> In Ace the front end, So there was an issue like you can't add the same project because I saw many contributors add the same project in another repo

Yes ik about it, what I meant was I saw a similar issue in one of the 3repos that I maintain. That's why was just confirming.

**Comment by gurjeetsinghvirdee** [comment]
> > > @gurjeetsinghvirdee did you raise this issue in some other repo as well?
> > 
> > 
> > In Ace the front end, So there was an issue like you can't add the same project because I saw many contributors add the same project in another repo
> 
> Yes ik about it, what I meant was I saw a similar issue in one of the 3repos that I maintain. That's why was just confirming.

yeah I also saw, but In front end template someone added a google clone but that was just HTML and CSS, don't know about other repo may be they also like design not work at all
