### ISSUE TITLE
Increment & Decrement COUNTER

### ISSUE THREAD

**Issue by SidharthSarangi** [arpit456jain/Amazing-Js-Projects#357]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

will be adding an increment/decrement counter using ReactJS with the help of hooks. And will also be adding comments to help further for easy understanding for beginners.
Please assign me this issue.
I am a GSSOC'22 participant.

**Comment by VidhiBhatt01** [comment]
The scope of this repo as of now is only projects with Vanilla JS
