### ISSUE TITLE
Sort the Projects 

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Amazing-Js-Projects#358]
Arrange the projects in a sequential way ( The way they are shown in GitHub). Changes are needed to be made in style_links.json.

![image](https://user-images.githubusercontent.com/83345228/158012379-90dd527a-9eba-40fd-ac33-3c7622ede8dd.png)

**Comment by mrkc2303** [comment]
Hey @VidhiBhatt01 

I can do this task efficiently.

**Comment by ez-sherlock** [comment]
@VidhiBhatt01 Hy, Please assign this task to me. I have read the source code already. I can do this easily. Thanks :)
