### ISSUE TITLE
Add search bar

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Amazing-Js-Projects#359]
Shift the title on left and include a search bar beside it so that projects can be searched and found easily

![image](https://user-images.githubusercontent.com/83345228/158012446-67ffc2da-b2bc-4bc9-ab8a-2c6154fbc111.png)

**Comment by ez-sherlock** [comment]
Hy @VidhiBhatt01 Please assign this task to me. Thanks :)

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01  Please assign this issue to me

**Comment by arpit456jain** [comment]
@Abh1shekSingh do this in PR for #324
