### ISSUE TITLE
I would like to make Tip calculator 

### ISSUE THREAD

**Issue by Naman-mahi** [arpit456jain/Amazing-Js-Projects#36]
I would like to make Tip calculator app, please assign me under DCP'21

**Comment by arpit456jain** [comment]
Go ahead @Naman-mahi

**Comment by arpit456jain** [comment]
@Naman-mahi any updates

**Comment by Naman-mahi** [comment]
Yes sir, tonight I'll create PR

**Comment by arpit456jain** [comment]
@Naman-mahi any updates ?
