### ISSUE TITLE
Spotify Clone

### ISSUE THREAD

**Issue by SidharthSarangi** [arpit456jain/Amazing-Js-Projects#363]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

will be adding the Spotify clone using HTML, CSS, JS
Please assign me to this.
I am GSSOC'22 participant.

**Comment by VidhiBhatt01** [comment]
Hey @SidharthSarangi, you can raise this issue in  cool frontend templates repo if a Spotify clone is not present there
