### ISSUE TITLE
Chat-app

### ISSUE THREAD

**Issue by aditi10701** [arpit456jain/Amazing-Js-Projects#367]
A chat app can be created which will provide user access to chat with users. I am interested in working with this project. Kindly assign me the same

**Comment by VidhiBhatt01** [comment]
What all tech stack would you use for this @aditi10701. Also add some SS or video if possible.

**Comment by astha2412** [comment]
@aditi10701 ???? Complete your issue within 3-4 days otherwise, I will close your issue!

**Comment by aditi10701** [comment]
Yes, this issue will be completed asap.

**Comment by VidhiBhatt01** [comment]
@aditi10701 any update?

**Comment by DEEPALI-SUK** [comment]
@aditi10701 ?

**Comment by VidhiBhatt01** [comment]
Reopen this when ready
