### ISSUE TITLE
Alarm Clock

### ISSUE THREAD

**Issue by SahilSingh177** [arpit456jain/Amazing-Js-Projects#368]
An alarm clock can be made with awesome features such as snooze, volume level, and selection of music from the user's system or from different web applications such as Spotify, etc.

**Comment by VidhiBhatt01** [comment]
> An alarm clock can be made with awesome features such as snooze, volume level, and selection of music from the user's system or from different web applications such as Spotify, etc.

This sounds cool!! Would be awaiting the PR :)

**Comment by astha2412** [comment]
@SahilSingh177 ???? Complete your issue within 3-4 days.

**Comment by pushpanjali-10** [comment]
I'm Contributor in GSSoC22 . Can u assign this to me.

**Comment by DEEPALI-SUK** [comment]
@SahilSingh177 ?? we will assign this issue to @pushpanjali-10 if u do not respond

**Comment by VidhiBhatt01** [comment]
Assigned the issue to you @pushpanjali-10

**Comment by pushpanjali-10** [comment]
Yes , i am working on it
