### ISSUE TITLE
Connect 4 Game

### ISSUE THREAD

**Issue by kiruba-r11** [arpit456jain/Amazing-Js-Projects#37]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

- Connect Four is a 6 * 7 grid-based two-player game. If a player matches any four cells consecutively (in a row, column, or diagonal), the player wins.

**Comment by kiruba-r11** [comment]
@arpit456jain  @ankitapuri I would like to work on this as a part of DCP'21

**Comment by ankitapuri** [comment]
@kiruba-r11 go ahead
