### ISSUE TITLE
JavaScript Audio Visualizer Background

### ISSUE THREAD

**Issue by Shubham56-droid** [arpit456jain/Amazing-Js-Projects#370]
It is basically a website background using canvas to make changes according to user audio input in the microphone.

**Comment by Shubham56-droid** [comment]
pls assign this issue to me under GSScC22

**Comment by DEEPALI-SUK** [comment]
@Shubham56-droid ???? Do this issue asap otherwise we will close this issue

**Comment by DEEPALI-SUK** [comment]
@Shubham56-droid I am closing this issue
