### ISSUE TITLE
Meditation Webpage

### ISSUE THREAD

**Issue by Kunal0220** [arpit456jain/Amazing-Js-Projects#374]
**Feature Request:**

A Meditation webpage which will ask the user what type of problem they have and based on that it will give them the yoga forms and asanas as feedback that they can practice to get over that particular problem.

It will be made on _HTML CSS JS_ .

I would like to work on this new feature.
Kindly assign it to me.
GSSoC'22 Contributor.

**Comment by DEEPALI-SUK** [comment]
@Kunal0220?? Do this issue asap otherwise we will close this issue

**Comment by Kunal0220** [comment]
Bhaiya I have started working on this , Actually my exams are going on thats why its taking long , I will try to finish it and make a PR asap, thank you for your time and patience 🙌🏻

**Comment by san-droid371** [comment]
Can I also contribute on this issue with @Kunal0220 . Please assign this issue #374 to me as well.

**Comment by Kunal0220** [comment]
I will make a PR today bro , Thanks for your help.
Happy Contributing 🙌🏻.

**Comment by san-droid371** [comment]
No issues. will look for the other 
Happy Contributing
