### ISSUE TITLE
Counter Feature to display current number of projects

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Amazing-Js-Projects#379]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

Want to add counter feature in the website which will tell and display the number of project displaying on the website

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![unknown](https://user-images.githubusercontent.com/71981463/158545755-ee300a99-c34b-4368-a824-cce8d9163c12.png)

**Comment by Abh1shekSingh** [comment]
@arpit456jain @VidhiBhatt01  Please assign this issue to me. I will solve it soon

**Comment by arpit456jain** [comment]
@Abh1shekSingh do three things in one PR

search
responsive ness
and UI change
