### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by RavishaNewase** [arpit456jain/Amazing-Js-Projects#380]
This app will keep track of daily activities to be done.
Can also edit or delete the activity.

**Comment by RavishaNewase** [comment]
Please assigned me under GSSoC'22

**Comment by DEEPALI-SUK** [comment]
@RavishaNewase ?? Do this issue asap otherwise we will close this issue

**Comment by RavishaNewase** [comment]
> @RavishaNewase ?? Do this issue asap otherwise we will close this issue
Yaa, just bcoz I had exams this week I could not complete, But I will do it by Saturday 26.
Hope, It suits you !
And please assign me this under GSSoC'22.....

**Comment by DEEPALI-SUK** [comment]
> > @RavishaNewase ?? Do this issue asap otherwise we will close this issue
> > Yaa, just bcoz I had exams this week I could not complete, But I will do it by Saturday 26.
> > Hope, It suits you !
> > And please assign me this under GSSoC'22.....

yeah

**Comment by RavishaNewase** [comment]
> > > @RavishaNewase ?? Do this issue asap otherwise we will close this issue
> > > Yaa, just bcoz I had exams this week I could not complete, But I will do it by Saturday 26.
> > > Hope, It suits you !
> > > And please assign me this under GSSoC'22.....
> 
> yeah

Heyy !  I had told you about submitting the issue by Saturday but bcoz of some other work I couldn't..... I will definitely submit the issue tomorrow..

**Comment by DEEPALI-SUK** [comment]
@RavishaNewase link the PR properly

**Comment by DEEPALI-SUK** [comment]
@RavishaNewase ?
