### ISSUE TITLE
Tiktok Clone

### ISSUE THREAD

**Issue by TG922** [arpit456jain/Amazing-Js-Projects#386]
## Issue Type:
- [ ]  Bug Report
- [x]  Feature Request
- [ ]  Documentaion

will be adding the Tiktok clone using HTML, CSS, JS
Please assign me to this, I am a GSSOC'22 participant

**Comment by VidhiBhatt01** [comment]
@TG922 make sure you don't copy it from anywhere and it's fully responsive. Also, if this project has less JS, I would suggest you close the issue here and raise it in Cool Frontend templates.

**Comment by TG922** [comment]
> @TG922 make sure you don't copy it from anywhere and it's fully responsive. Also, if this project has less JS, I would suggest you close the issue here and raise it in Cool Frontend templates.

OK @VidhiBhatt01

**Comment by astha2412** [comment]
@TG922 open this issue in cool frontend templates. I m closing this issue!
