### ISSUE TITLE
Live User Filter

### ISSUE THREAD

**Issue by Avik-creator** [arpit456jain/Amazing-Js-Projects#391]
## Feature Request

- Want to add a Live User Filter.

**Comment by arpit456jain** [comment]
@Avik-creator r u sure the projects u r trying to add are original because if we found any one project under plag ur all PRs will be check again

**Comment by Avik-creator** [comment]
I will be making it by seeing tutorial.

**Comment by arpit456jain** [comment]
@Avik-creator mention the resources

**Comment by Avik-creator** [comment]
I will be making it by seeing tutorial.
Traversey media 5 amazing js projects.

**Comment by Avik-creator** [comment]
https://youtu.be/JkeyKeK3V24
Here is the link @arpit456jain

**Comment by Avik-creator** [comment]
Please go to the part 4 of the video

**Comment by Avik-creator** [comment]
@arpit456jain will this issue be assigned to me?

**Comment by VidhiBhatt01** [comment]
@Avik-creator Don't copy it totally from the video. Make it responsive for all screen sizes, change the theme/add something on your own, and mention the link of this video as a reference in the PR description.

**Comment by Avik-creator** [comment]
I will change it and then change the screen shot ma'am
