### ISSUE TITLE
Add Windows 11

### ISSUE THREAD

**Issue by Avik-creator** [arpit456jain/Amazing-Js-Projects#392]
## Feature Request:

- Want to add windows 11 which will be made by using JavaScript.

**Comment by arpit456jain** [comment]
what will it do ?

**Comment by Avik-creator** [comment]
It will be just like a template an interactive one using javascript. I will be making it using code with Harry tutorial. But there will be changes in icon packs, etc

**Comment by arpit456jain** [comment]
link

**Comment by Avik-creator** [comment]
https://youtu.be/OtOmxa9UMe8
Here is the link @arpit456jain

**Comment by Avik-creator** [comment]
@arpit456jain will this issue be assigned to me?

**Comment by astha2412** [comment]
@arpit456jain ??????

**Comment by Avik-creator** [comment]
Thank you

**Comment by DEEPALI-SUK** [comment]
@Avik-creator any updates?

**Comment by Avik-creator** [comment]
I will work on it sir

**Comment by Avik-creator** [comment]
I haven't done yet but expect to have news in 2 days

**Comment by Avik-creator** [comment]
@DEEPALI-SUK
