### ISSUE TITLE
lots of images are missing 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#395]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by prabhkaur301** [comment]
## Bug Description
In style.json , there is array of objects containing the folder name and path to index.html. The display image (named preview.png) is picked from that mentioned folder. For those projects , where image is not shown , there is no preview.png in their project folder or the name in json file is not same as that of project folder name.

Assign this to me, I'll solve this bug

**Comment by arpit456jain** [comment]
go ahead @prabhkaur301

**Comment by arpit456jain** [comment]
also check the extension shold be png not jpg or jpeg
