### ISSUE TITLE
PNG to PDF convertor

### ISSUE THREAD

**Issue by Abhishek786-Kolvekar** [arpit456jain/Amazing-Js-Projects#399]
Tech stack: HTML, CSS and JS
Demo video: Below

**Comment by Abhishek786-Kolvekar** [comment]
https://user-images.githubusercontent.com/81409657/159129530-42b20363-ee49-4574-afde-19f63feaedf4.mp4

**Comment by Abhishek786-Kolvekar** [comment]
Please assign this issue to me.

**Comment by Abhishek786-Kolvekar** [comment]
Any suggestions from your side. Any addons. Please let me know.
@astha2412 @arpit456jain

**Comment by arpit456jain** [comment]
@Abhishek786-Kolvekar make PR so that we can review and make sure it should be responsive

**Comment by astha2412** [comment]
@Abhishek786-Kolvekar If u r facing any problem in making PR then let us know, but complete this PR asap!

**Comment by Abhishek786-Kolvekar** [comment]
Hello @astha2412 @arpit456jain 
The problem is with responsiveness, its not working.
But functionality-wise its perfect .

**Comment by Abhishek786-Kolvekar** [comment]
Even I have my university lab externals scheduled from the 28th. So, I am facing difficulty.
Should I send PR now?

**Comment by Abhishek786-Kolvekar** [comment]
Do check my PR
#409

**Comment by astha2412** [comment]
> Even I have my university lab externals scheduled from the 28th. So, I am facing difficulty. Should I send PR now? I take the responsibility of bringing the responsiveness soon after the exam gets over.

@arpit456jain what to do now??

**Comment by Abhishek786-Kolvekar** [comment]
Hello @astha2412 and @arpit456jain.
I am extremely sorry for causing such an issue.
The best you can do is to close the PR and the issue since it was not meeting up the expectations. I am absolutely fine with it.
I will request this issue once my exams get over.
