### ISSUE TITLE
Add Project Mentors

### ISSUE THREAD

**Issue by DEEPALI-SUK** [arpit456jain/Amazing-Js-Projects#400]
## **Describe the bug**

Add two mentors in the project mentors section.
Here are there Github links-
https://github.com/DEEPALI-SUK
https://github.com/DEEPIKA-SUK

**Comment by shivam123-dev** [comment]
I am GSSoC22 contributor. Kindly assign me this issue.

**Comment by shivam123-dev** [comment]
@DEEPALI-SUK Kindly review my PR
