### ISSUE TITLE
Add Number System Converter.

### ISSUE THREAD

**Issue by VagishaGupta9** [arpit456jain/Amazing-Js-Projects#402]
I want to add a number system converter.
I'm a gssoc'22 participant.

**Comment by SonikeshKumar14** [comment]
plz i requested you assign to me

**Comment by VagishaGupta9** [comment]
@SonikeshKumar14 stop spamming in every issue or i have to take strict action against you.

**Comment by SonikeshKumar14** [comment]
> @SonikeshKumar14 stop spamming in every issue or i have to take strict action against you.
I am sorry it's my fault

**Comment by SonikeshKumar14** [comment]
hey untill you are not assigned how you say i am spamming?
you are not a mentor for this project

**Comment by SonikeshKumar14** [comment]
if you will be assigned then i myself go out.
I am asking only for assiging of issues. i am not abuse anybody.
every issue opened but not assigned .
so i have a right to ask for assigning issues

**Comment by SonikeshKumar14** [comment]
only two issues i am asking  and you are telling i am spamming.
i myself take strict action against your okay!!!!

**Comment by SonikeshKumar14** [comment]
Examples of unacceptable behavior by participants include:

Violence, threats of violence, or inciting others to commit self-harm
The use of sexualized language or imagery and unwelcome sexual attention or advances
Trolling, intentionally spreading misinformation, insulting/derogatory comments, and personal or political attacks
Public or private harassment
Publishing others' private information, such as a physical or electronic address, without explicit permission
Abuse of the reporting process to intentionally harass or exclude others
Advocating for, or encouraging, any of the above behavior
Other conduct which could reasonably be considered inappropriate in a professional setting

**Comment by SonikeshKumar14** [comment]
read this upward comment I am not break any rules.
