### ISSUE TITLE
Number Machine

### ISSUE THREAD

**Issue by NikhilMahana** [arpit456jain/Amazing-Js-Projects#403]
It takes a number and tells you what it is divisible by. You can check the numbers features through it like, determine the given number is prime or not, check its divisors, square root, and cube root. You just have to type the number and click on the submit button to display the information on the numbers

**Comment by astha2412** [comment]
@NikhilMahana Attach some ss or video

**Comment by DEEPALI-SUK** [comment]
@NikhilMahana ????
