### ISSUE TITLE
Function Grapher

### ISSUE THREAD

**Issue by XZANATOL** [arpit456jain/Amazing-Js-Projects#405]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

A JS app that plots a function of x -> f(x). Example:
* x
* x^2 + 2x + 5
* sin(x)

## **Possible solution**

The app will make use of: HTML / CSS / JS / Bootstrap5

## **Screenshots**

![image](https://user-images.githubusercontent.com/64689436/159187959-b30dddd1-0c02-4a85-ad72-cfc42d791e47.png)

**Comment by astha2412** [comment]
@XZANATOL I will suggest open your issue in Cool frontend templates, as this issue contains HTML, CSS, JS, Bootstrap.

**Comment by XZANATOL** [comment]
It's main functionality lies in JS. I just used bootstrap to stylize the shape a bit instead of making the page full wjite.
