### ISSUE TITLE
Fortune Cookie Generator

### ISSUE THREAD

**Issue by abhilipsasahoo03** [arpit456jain/Amazing-Js-Projects#407]
# Feature Request

A fortune cookie is a small dessert containing a slip of paper with prediction or motto written on it. 

I'd like to add a Fortune Cookie Message Generator which can generate fortune cookie sayings while also keeping a record of previous fortune cookie messages generated. 

Please assign me this issue under GSSOC'22

**Comment by DEEPALI-SUK** [comment]
@abhilipsasahoo03 ???

**Comment by abhilipsasahoo03** [comment]
> @abhilipsasahoo03 ???

Hi, sorry for the delay. I'll be making a PR by today.
