### ISSUE TITLE
Pacman Game

### ISSUE THREAD

**Issue by git-pi-e** [arpit456jain/Amazing-Js-Projects#410]
# Feature Request:

## Pacman game using Javascript

I wish to build a [Pacman Game](https://en.wikipedia.org/wiki/Pac-Man) using Javascript.

The Tech stack that I'll be using will be:
- HTML
- SCSS
- Vanilla JS

Kindly assign me this task under GSSoC'22.

**Comment by DEEPALI-SUK** [comment]
@git-pi-e ???

**Comment by git-pi-e** [comment]
> @git-pi-e ???

I've started working on this. Board and characters have been implemented. Player functions and the respective GUI will be my next task.

**Comment by DEEPALI-SUK** [comment]
@git-pi-e ???

**Comment by DEEPALI-SUK** [comment]
Do this issue asap otherwise we will close this issue

**Comment by git-pi-e** [comment]
> Do this issue asap otherwise we will close this issue

I'm really sorry to reply late due to my exams. I'm almost done with player functions as well.

**Comment by astha2412** [comment]
OK @git-pi-e Make PR asap!
