### ISSUE TITLE
Quiz App with Better UI Design  Using Javascript,CSS and Html

### ISSUE THREAD

**Issue by Ankit62042** [arpit456jain/Amazing-Js-Projects#416]

**Comment by Ankit62042** [comment]
may I work on this issue ?

**Comment by VidhiBhatt01** [comment]
How will you improve the UI? Ie. what changes will you make? Elaborate in detail and add some SS of older UI to explain the same.

**Comment by Ankit62042** [comment]
![Uploading Screenshot (158).png…]()

**Comment by Ankit62042** [comment]
![Screenshot (158)](https://user-images.githubusercontent.com/71378462/160287018-5db9fffc-d29b-4fc5-a775-6116a98dbf6b.png)

**Comment by Ankit62042** [comment]
Hii @VidhiBhatt01, This is the UI Design of the Quiz project. When User will Submit First question then He/she Will move to next question and After Compleating the quiz Final Soore Will be Shown

**Comment by Ankit62042** [comment]
![Uploading Screenshot (159).png…]()

**Comment by Ankit62042** [comment]
![Uploading Screenshot (159).png…]()

**Comment by Ankit62042** [comment]
![Screenshot (159)](https://user-images.githubusercontent.com/71378462/160287321-d2d977ea-2b78-4283-aaa8-e72b035f161d.png)

**Comment by Ankit62042** [comment]
To represent Socre I used Card and also added Play again button so that User will play quiz again

**Comment by Ankit62042** [comment]
May I send you a PR for this project?

**Comment by DEEPALI-SUK** [comment]
@Ankit62042 quiz app is already there. Are there some extra features in your app?
