### ISSUE TITLE
collabration white board

### ISSUE THREAD

**Issue by roy-shivam** [arpit456jain/Amazing-Js-Projects#418]
## Issue Type:

Want to add a JavaScript project.

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help exp
![demo-video](https://user-images.githubusercontent.com/85537444/159755550-68f4dd62-0a87-4786-9863-ad921e8bd814.gif)
![white](https://user-images.githubusercontent.com/85537444/159755583-2c72cc5d-0b1f-4c64-837e-e501792e8339.gif)
lain your problem.

**Comment by roy-shivam** [comment]
please assign me this under GSSOC 2022.

**Comment by DEEPALI-SUK** [comment]
@roy-shivam are u working on this?
