### ISSUE TITLE
Add a split Landing page

### ISSUE THREAD

**Issue by kheya19** [arpit456jain/Amazing-Js-Projects#420]
I can make a landing page that is split into two halves but  on hovering one expands and the other one shrinks

**Comment by DEEPALI-SUK** [comment]
@kheya19 show us the demo of the final project, if it will be good we will assign u

**Comment by kheya19** [comment]
> @kheya19 show us the demo of the final project, if it will be good we will assign u

Ok

**Comment by VidhiBhatt01** [comment]
@kheya19 any update?

**Comment by kheya19** [comment]
> @kheya19 any update?

Yes I have made it.

**Comment by VidhiBhatt01** [comment]
Did you raise the PR for the same?
