### ISSUE TITLE
Remove the horizontal scroll in mobile view

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#422]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

<img width="209" alt="image" src="https://user-images.githubusercontent.com/55352601/159872083-ab548670-ce28-481c-a3a2-ae857490d9b1.png">

**Comment by Abh1shekSingh** [comment]
Assign it to me please
