### ISSUE TITLE
Lots of preview pics are missing and lots of projects are there which are not added in json file

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#423]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by gurjeetsinghvirdee** [comment]
Assign me

**Comment by arpit456jain** [comment]
Sorry but this issue is already present and someone is working on it
I m closing it for now i will reopen it if this issue remains
@gurjeetsinghvirdee
