### ISSUE TITLE
Falling-Ball-Game

### ISSUE THREAD

**Issue by priyanshu688** [arpit456jain/Amazing-Js-Projects#432]
Wanted to add Falling Ball Game, project build with JavaScript Language

**Comment by priyanshu688** [comment]
I am a contributor under GSSoC'22. Kindly assign this me @arpit456jain

**Comment by VidhiBhatt01** [comment]
Assigned, it is to be noted that we are only accepting Vanilla JS projects as of now. If you are using React for it, kindly close this issue.

**Comment by priyanshu688** [comment]
The project is basically a small JavaScript project. @VidhiBhatt01

**Comment by priyanshu688** [comment]
@arpit456jain Kindly review and merge this- https://github.com/arpit456jain/Amazing-Js-Projects/pull/439
