### ISSUE TITLE
Digital + Analog clock 

### ISSUE THREAD

**Issue by Kumar-Ankit56** [arpit456jain/Amazing-Js-Projects#434]
I'm a contributor to GSSoc22.  This is an awesome project in JavaScript.

### Idea behind the project.
We all have often big, small clocks available in our hope, when we travel we visit some digital clock somewhere like railway station and metro station anywhere. This project is the combination of both clocks.

### How the project works.

- It simply takes date from your local machine and starts spinning their clock hands according. Parallelly, you will be able to observe the analog clock time in digital form.

please assign me this issue.

Thanks.

**Comment by VidhiBhatt01** [comment]
Sorry but we already have many clocks!!
