### ISSUE TITLE
Street Fighter VIII

### ISSUE THREAD

**Issue by DinahWorld** [arpit456jain/Amazing-Js-Projects#435]
## Issue Type:

- [ ] Bug Report
- [X] Feature Request
- [ ] Documentaion

I would like to add my game that I made during my classes into your project, the game plays itself but if you agree to put it I will add a 1vs1 mode, the code can be a bit messy and poorly optimized, and the game is a bit weight heavy sorry for that 🙏🏽.

## **Screenshots**
![stage_2](https://user-images.githubusercontent.com/88936472/160251055-8f95f701-170b-43c0-b09b-f7daba1edb2b.png)
![stage_1](https://user-images.githubusercontent.com/88936472/160251057-38be1ffb-4402-4551-8440-fe85f920f637.png)

Game Link : https://dinahworld.github.io/University-Fighter-VIII/
The repository : https://github.com/DinahWorld/University-Fighter-VIII

**Comment by VidhiBhatt01** [comment]
@arpit456jain

**Comment by arpit456jain** [comment]
ok @DinahWorld make it 1 vs 1 and try to optimized it

**Comment by DinahWorld** [comment]
It will be done 😉 @arpit456jain

**Comment by DEEPALI-SUK** [comment]
@DinahWorld Do this issue asap otherwise we will close this issue

**Comment by DinahWorld** [comment]
sorry for not answering you, I'm overwhelmed at the moment, I'll do this issue later
