### ISSUE TITLE
Star-rating with JS.

### ISSUE THREAD

**Issue by Kumar-Ankit56** [arpit456jain/Amazing-Js-Projects#440]
I'm GSSoc contributer. This is a star rating project using Javascript.
### Idea behind the project.
Like whenever we order any product from online store so after delivery they seeking for review, it contain a box with black star and a text area.

### How does it works,
Similar kind of project idea I have or even clone. Like there will be 5 star, you have Select it as much you will select out of 5 it will glow and as per matched rating there will expression preview as 1 for aweful 5 for brilliant.

Please assign me this issue, so that I can work further.

Thanks.

**Comment by DEEPALI-SUK** [comment]
@Kumar-Ankit56 Do this issue asap otherwise we will close this issue
