### ISSUE TITLE
T-rex runner game 

### ISSUE THREAD

**Issue by RAHULBAWA777** [arpit456jain/Amazing-Js-Projects#445]
T-rex runner game that appears in the web browser when you are not connected to  the internet

**Comment by DEEPALI-SUK** [comment]
@RAHULBAWA777 Do this issue asap otherwise we will close this issue

**Comment by RAHULBAWA777** [comment]
Yeah I'm working on it

**Comment by astha2412** [comment]
Make PR asap!
