### ISSUE TITLE
Emoji slider

### ISSUE THREAD

**Issue by Kumar-Ankit56** [arpit456jain/Amazing-Js-Projects#448]
Hii I'm a GSSoc22 contributor and I'm looking to make a pr request in this repo regarding my project which is a custom emoji slider.

### The idea behind this project
This is a very mini project of an e-commerce site, as whenever we visit any site then after purchasing there is a popup for giving a review regarding the project. sometimes you have to give in a star rating or you can have an emoji slider by which you can express yourself, so the idea is from there only.

###How does it work
whenever you will slide the range bar then after with respect to range there will match emoji preview and parallelly you will observe background changing.

please refer to this image
![Screenshot (96)](https://user-images.githubusercontent.com/73521123/160627997-633834f0-92d2-4605-8f4b-e08e27d30a38.png)
![Screenshot (97)](https://user-images.githubusercontent.com/73521123/160628009-834798bd-315c-438c-a8ac-bc6d1e9b9a8a.png)

Thanku

**Comment by VidhiBhatt01** [comment]
Interesting!

**Comment by eswarbhageerath** [comment]
Sir ,I would like to work on this project , already I have some experience regarding this work , please assign this to me😁...Thank you sir

**Comment by DEEPALI-SUK** [comment]
@Kumar-Ankit56 Do this issue asap otherwise we will assign this issue to someone else
