### ISSUE TITLE
Make Typer Game Responsive

### ISSUE THREAD

**Issue by DEEPALI-SUK** [arpit456jain/Amazing-Js-Projects#450]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

Make the Typer game responsive such that fonts should be clearly visible in mobile view and add a keyboard on the screen for mobile view.

**Comment by AnIkeT126** [comment]
@arpit456jain  assign this to me

**Comment by astha2412** [comment]
@DEEPALI-SUK ?

**Comment by DEEPALI-SUK** [comment]
https://github.com/arpit456jain/Amazing-Js-Projects/pull/443
this one , folder name Typer

**Comment by AnIkeT126** [comment]
Will make a PR, by tonight, if that's fine

**Comment by AnIkeT126** [comment]
> @AnIkeT126 u got it ?

@arpit456jain check PR #567

**Comment by AnIkeT126** [comment]
> > @AnIkeT126 u got it ?
> 
> @arpit456jain check PR #567

@arpit456jain @VidhiBhatt01 please provide a level label for evaluation.
Thanks in advance.
