### ISSUE TITLE
Linked List Visualizer 

### ISSUE THREAD

**Issue by omkar806** [arpit456jain/Amazing-Js-Projects#453]
Hey this is Omkar Malpure GSSOC'22 contributor  and I'm looking to make a pr request in this repo regarding my project  that is the Linked List visualizer.

_**The idea behind this project :**_ 
So this is a mini-project where user can actually visualize a linked list which is one of the most important data structure . So here I have added all the operations of the linked list like insert,update,delete,etc of the linked list , using javascript and also used html and CSS to make the project look attaractive . This was a very fun project and also it may get the concept of the linked list get very clear for the beginners in Data Structures and Algorithms.

## **Screenshots**
![image](https://user-images.githubusercontent.com/77787482/160965757-0a02f5a2-786e-4203-b5bb-e662d1f29379.png)

![image](https://user-images.githubusercontent.com/77787482/160965801-de76eb33-a32b-43e8-8353-1d8cee07120f.png)

**Comment by omkar806** [comment]
Hey @arpit456jain please assign this issue to me ...

**Comment by VidhiBhatt01** [comment]
Assigning, but make sure it's fully responsive and not plagiarised.

**Comment by omkar806** [comment]
yes its fully responsive

**Comment by astha2412** [comment]
Make new issue when u r ready @omkar806
