### ISSUE TITLE
Car Racing Game

### ISSUE THREAD

**Issue by itsmohitnamdeo** [arpit456jain/Amazing-Js-Projects#454]
I am GSSOC'22 Contributor
I wanted to add Car Racing JS project... 
Car Racing Game is one of the best and fun Js Project..

**Comment by VidhiBhatt01** [comment]
@arpit456jain

**Comment by arpit456jain** [comment]
@itsmohitnamdeo make the PR but try to reduce its size

**Comment by arpit456jain** [comment]
@itsmohitnamdeo
