### ISSUE TITLE
Moto Racing Car

### ISSUE THREAD

**Issue by Priyanshi136** [arpit456jain/Amazing-Js-Projects#456]
It's a javascript game.  I want to contribute to this project by adding this game as an Gssoc'22 contributor.

**Comment by pushpanjali-10** [comment]
Hey, I am a contributor of GSSoc'22. Can you assign me this issue ?

**Comment by VidhiBhatt01** [comment]
@Priyanshi136 make sure that the project size is not too large.

**Comment by Priyanshi136** [comment]
okay, and i will try to raise PR as soon as i can.

**Comment by astha2412** [comment]
@Priyanshi136 ?

**Comment by astha2412** [comment]
MAke new issue when u r ready!
