### ISSUE TITLE
Game-of-pong

### ISSUE THREAD

**Issue by tanktejas** [arpit456jain/Amazing-Js-Projects#459]
=> It is a game of pong. in which player playing with the computer.
=> it will look like below image.

![Screenshot (225)](https://user-images.githubusercontent.com/77108255/161317485-1a1a89af-35b1-4308-aaf5-64f08d9cd32f.png)

**Comment by VidhiBhatt01** [comment]
You must raise the PR only after the issue is assigned to you. Allowing it this time, but keep this in mind while making further contributions
