### ISSUE TITLE
Make a Seperate page for Calculators and move all calculators to that page

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#46]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Dhruv-194** [comment]
@arpit456jain can I work on this issue?

**Comment by arpit456jain** [comment]
ok @Dhruv-194

**Comment by arpit456jain** [comment]
@Dhruv-194 any updates ??

**Comment by Dhruv-194** [comment]
@arpit456jain Yes i will be surely working on this today and send to you by evening. Actually I had a lot of merge conflicts with my repository because of the current changes which happened to this repository. So I was handling them.

**Comment by arpit456jain** [comment]
Ok 
And don't worry now there is no more PRs to be merged

**Comment by arpit456jain** [comment]
@Dhruv-194  ??

**Comment by Dhruv-194** [comment]
@arpit456jain yes I have finished it. Will send the PR shortly.
