### ISSUE TITLE
Pixel to Em and Em to pixel converter.

### ISSUE THREAD

**Issue by Kumar-Ankit56** [arpit456jain/Amazing-Js-Projects#462]
Hii I'm a GSSoc22 contributor and I'm looking to make a pr request in this repo regarding my project which is a custom emoji slider.

### The idea behind this project
This is just like calculating which is performing calculation behind the scene.

### How does it work
Here is three input field upper one is the base value and below two input box with px and em level this is CSS unit. when we will put some value in px it will evaluate em value accordingly behind the scene and will preview in em field. Simlarly we have vice verse function as well Em to Pixel

for more details please refer to this attached images.
![Screenshot (98)](https://user-images.githubusercontent.com/73521123/161326669-646c6d91-90bd-415f-b514-a01d7f66be00.png)
![Screenshot (99)](https://user-images.githubusercontent.com/73521123/161326681-a319e878-665a-4032-893b-c3f2cdf0e13b.png)

**Comment by Kumar-Ankit56** [comment]
Thanks for assigning me,
I have a doubt we are getting the label of the level just one attached by bot which is GSSoc22.
Kindly review my problem

**Comment by Kumar-Ankit56** [comment]
> Thanks for assigning me, I have a doubt we are getting the label of the level just one attached by a bot which is GSSoc22. Kindly review my problem

**Comment by astha2412** [comment]
Make PR then u will get more labels. Make PR asap! @Kumar-Ankit56

**Comment by Kumar-Ankit56** [comment]
Yeah all done I will do soon,

**Comment by VidhiBhatt01** [comment]
Open this when ready
