### ISSUE TITLE
Add Interactive Resume 

### ISSUE THREAD

**Issue by itsmohitnamdeo** [arpit456jain/Amazing-Js-Projects#464]
I wanted to add Gaming Template in this project...
![ir1](https://user-images.githubusercontent.com/85800451/161363067-5aac1f49-4161-41dc-b634-1fbd005d72e9.png)
![ir2](https://user-images.githubusercontent.com/85800451/161363070-ff5a8f8f-cd97-42c6-9309-22fe5eaa439f.png)

**Comment by VidhiBhatt01** [comment]
Try to reduce the project size as much as possible

**Comment by astha2412** [comment]
@itsmohitnamdeo ???
