### ISSUE TITLE
Catch Insect

### ISSUE THREAD

**Issue by itsmohitnamdeo** [arpit456jain/Amazing-Js-Projects#466]
Insect game is a JS game to catch insect..
![Catch-insect](https://user-images.githubusercontent.com/85800451/161364206-681e63da-10b4-4432-8644-713d3f2a08dc.png)
![Catch-insect2](https://user-images.githubusercontent.com/85800451/161364212-ea9166cd-8a28-4425-8a6e-1d54df393c41.png)

**Comment by astha2412** [comment]
@itsmohitnamdeo ?? Don't spam with your issues! First, make PR of one issue then open another one!
