### ISSUE TITLE
Add Live Chatbot

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [arpit456jain/Amazing-Js-Projects#473]
## Issue Type:

- [x] Feature Request

## **Describe the bug**
Not a bug it's a feature, I want to add a live chatbot with chatwoot

- A clear and concise description of what the bug is.

## **Screenshots**
Something like this I added in gssoc website PR not merged so you can't see their

<img width="341" alt="Screenshot 2022-04-05 000614" src="https://user-images.githubusercontent.com/73753957/161609496-8162e611-b9b5-4f7e-bb36-4b78dc97f4d0.png">

**Comment by sampavaranasi** [comment]
@arpit456jain @DEEPALI-SUK https://github.com/girlscript/gssoc-website-new/issues/70

**Comment by Suvraneel** [comment]
@sampavaranasi  This PR is already tagged invalid... Don't worry
