### ISSUE TITLE
Height Conversion Tool

### ISSUE THREAD

**Issue by kalashvasaniya** [arpit456jain/Amazing-Js-Projects#475]
<img width="492" alt="Screenshot 2022-04-05 at 4 34 03 PM" src="https://user-images.githubusercontent.com/88212870/161740479-7be77aa9-17b1-474c-80ed-bab3695fff81.png">

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.
