### ISSUE TITLE
Maths Addition Game

### ISSUE THREAD

**Issue by kalashvasaniya** [arpit456jain/Amazing-Js-Projects#476]
Like this:
<img width="694" alt="Screenshot 2022-04-05 at 4 35 30 PM" src="https://user-images.githubusercontent.com/88212870/161740667-f884c8ce-5372-4f60-bd62-4193cdb25f46.png">

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.
