### ISSUE TITLE
Chrome-Pinterest-Extension

### ISSUE THREAD

**Issue by ranimanya** [arpit456jain/Amazing-Js-Projects#479]
Here I intend to create a Pinterest extension in Chrome browser using html, css and javascript. 
It helps us collect, organize, save and revisit our inspiring ideas whenever we wish to.

Please assign me this issue, I'm a *GSSoc22* participant.

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.
