### ISSUE TITLE
Tower building game

### ISSUE THREAD

**Issue by prer45** [arpit456jain/Amazing-Js-Projects#481]
This game intends to stack as many boxes on top of each other as possible. When you click on the screen , the bouncing box starts to fall. Unless you click in the moment when the two boxes are ideally aligned, the part of the box that is sticking out falls off the screen and the next box has less room for landing.
I would like to work on this game.

Please assign it to me for GSSOC'22

**Comment by arpit456jain** [comment]
@prer45 i can only accept it if its made by u with out using any online help

**Comment by prer45** [comment]
> @prer45 i can only accept it if its made by u with out using any online help

okayy I will try my best

**Comment by VidhiBhatt01** [comment]
@arpit456jain

**Comment by arpit456jain** [comment]
ok @prer45 work on it make sure it should be original

**Comment by arpit456jain** [comment]
@prer45

**Comment by prer45** [comment]
> @prer45

pls give me 2 more days time as I was little busy with clg work

**Comment by VidhiBhatt01** [comment]
@prer45 any updates?

**Comment by astha2412** [comment]
@prer45 Make issue again when u r ready with your code!
