### ISSUE TITLE
PET RESCUE

### ISSUE THREAD

**Issue by ritweekraj2802** [arpit456jain/Amazing-Js-Projects#482]
Helloo sir/ma'am , I have participated in GSSOC 22 and I want to contribute in this project . Please assign me .

PROJECT DETAIL:

Pet Rescue

Key concepts covered:
-Factory functions
-Object methods and properties

What to do:
I am going to implement the JavaScript code so that we can accept an animal’s name, species, and energy level as a parameter and indicate each animal’s status (whether they are sleeping or awake).

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.
