### ISSUE TITLE
Snake game using speech recognition

### ISSUE THREAD

**Issue by ranimanya** [arpit456jain/Amazing-Js-Projects#487]
I intend to add a snake game which is voice controlled. It utilizes 'up', 'left', 'right', 'down' commands for moving the snake so that it can reach its food and consume it to become bigger in size by one unit every time it encounters food.

Please assign me this issue, I'm a GSSoC22 participant.

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.
