### ISSUE TITLE
Adding issue forms to the Repo

### ISSUE THREAD

**Issue by MonarchGitHub** [arpit456jain/Amazing-Js-Projects#489]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- I was about to submit an issue regarding my project and I noticed that this repo doesn't have any issue forms. Issue forms make it very convenient for the contributors to create new issues.

## **Possible solution**

- I want to add a few issue Forms so that it will be convenient for new contributors to open issues. I plan to create  **Bug Report** and **Feature Request** Forms. You can read more about issue forms [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)

**_The Bug Report issue form will have the following fields_**

- **Description of the bug**
- **How to Reproduce**
- **Urgency indicator**

**_The Feature Request issue form will have the following fields_**

- **Is your feature request related to a problem? Please describe.**
- **Describe the solution you'd like**

**Comment by MonarchGitHub** [comment]
Kindly assign this issue to me.

**Comment by VidhiBhatt01** [comment]
@arpit456jain

**Comment by astha2412** [comment]
@arpit456jain

**Comment by arpit456jain** [comment]
@MonarchGitHub what type of issue form i think we have issue template

**Comment by arpit456jain** [comment]
share some ss @MonarchGitHub

**Comment by MonarchGitHub** [comment]
Yeah, they're different from issue templates, here's an ss of how they look @arpit456jain 
![image](https://user-images.githubusercontent.com/74449136/162862317-16fc73d5-0b4b-4768-ba5a-8323ea5ea9b7.png)

**Comment by arpit456jain** [comment]
Its not needed for now
