### ISSUE TITLE
Number Facts

### ISSUE THREAD

**Issue by eswarbhageerath** [arpit456jain/Amazing-Js-Projects#493]
Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Number Facts.

The idea behind this project
This is a very mini project which can be used to know some fun facts about numbers. This will help not only in getting fun but also unknown knowledge and information about numbers

###How does it work
Whenever you enter a number in the input box and click submit, we can see some fact about that number.

please refer to these images

![ss1](https://user-images.githubusercontent.com/76146796/162207885-92db644b-ad48-41f3-8db0-3a0c06189b07.png)
![ss2](https://user-images.githubusercontent.com/76146796/162207899-1a5922a8-0ef1-4e8d-9e4e-1aeb4187879c.png)

**Comment by VidhiBhatt01** [comment]
We are not accepting new projects as of now. Keep an eye on the announcement channel on discord of this repo for further instructions.

**Comment by eswarbhageerath** [comment]
So, for the same year GSSOC, in up coming days , will there be any chance for new projects?? Or is it totally ended for GSSOC 2022??
