### ISSUE TITLE
I want to add a New Year countDown project to the Amazing Js project repository

### ISSUE THREAD

**Issue by AmolShelke2** [arpit456jain/Amazing-Js-Projects#499]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

- it is not a bug it is a project that I want to add.

## **Possible solution**

- Hey project admin I'm a GSSOC participant and I have come up with your project and I would love to contribute to your project one more time I want to add a New year countdown project it is a very basic project for beginners who don't know how to work with dates and DOM it can give them an idea of how things work so I hope that you will go through my issue and assign me this issue to work on...

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![New Year Countdown - Google Chrome 10-04-2022 12 24 49 PM](https://user-images.githubusercontent.com/95171638/162608899-050e3d26-19fe-4a29-a8f8-5b872c5af017.png)

## Deployment link 
[NEW YEAR COUNTDOWN](https://new-year-countdown-psi.vercel.app/)

**Comment by Pranav108** [comment]
I would love to work on it?, can I take it
