### ISSUE TITLE
Amazing wave effect

### ISSUE THREAD

**Issue by kalashvasaniya** [arpit456jain/Amazing-Js-Projects#502]
like this!

https://user-images.githubusercontent.com/88212870/162837013-3635caa7-196d-4e9c-a359-dce065472567.mov

**Comment by VidhiBhatt01** [comment]
Are you gonna use a significant amount of JS in this? If not, raise this issue in amazing CSS effects repo

**Comment by kalashvasaniya** [comment]
> Are you gonna use a significant amount of JS in this? If not, raise this issue in amazing CSS effects repo

Yes I use significant amount JS in that!
