### ISSUE TITLE
YOUTUBE CLONE

### ISSUE THREAD

**Issue by AnIkeT126** [arpit456jain/Amazing-Js-Projects#506]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

Adding a youtube clone

## **Possible solution**

A youtube clone using HTML5, CSS3 & JS

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by AnIkeT126** [comment]
@arpit456jain and @VidhiBhatt01 please assign this issue to me.

**Comment by AnIkeT126** [comment]
@arpit456jain and @VidhiBhatt01 please assign this issue to me.

**Comment by AnIkeT126** [comment]
@arpit456jain and @VidhiBhatt01 please assign this issue to me asap.

**Comment by VidhiBhatt01** [comment]
This repo is not for templates/clones
