### ISSUE TITLE
Wordle Clone

### ISSUE THREAD

**Issue by AnIkeT126** [arpit456jain/Amazing-Js-Projects#507]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

Wordle Clone, is a game played using the formation of words.

## **Possible solution**

Built using HTML, CSS, and JavaScript along with animate.css and toastr for non-blocking notifications.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by AnIkeT126** [comment]
@arpit456jain and @VidhiBhatt01 please assign this issue to me

**Comment by AnIkeT126** [comment]
@arpit456jain and @VidhiBhatt01 please assign this issue to me.

**Comment by AnIkeT126** [comment]
@arpit456jain and @VidhiBhatt01 please assign this issue to me.

**Comment by VidhiBhatt01** [comment]
This repo is not for templates/clones
