### ISSUE TITLE
Adding a certificate generator website

### ISSUE THREAD

**Issue by itzwow** [arpit456jain/Amazing-Js-Projects#508]
You just need to type the name of the participant and can generate the certificate as per predefined template

Tech stack used:
- HTML
- CSS
- JavaScript

Here is the screenshot:
![cert](https://user-images.githubusercontent.com/84179065/163121001-e94001d0-f39c-4fc1-9ceb-f5ff60ada51a.jpg)

I am GSSoC'22 participant and wanted to work upon it.

**Comment by riyajaiswal25** [comment]
I want to work on this
