### ISSUE TITLE
Facebook-HomePage-Clone

### ISSUE THREAD

**Issue by Susmita-Dey** [arpit456jain/Amazing-Js-Projects#514]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**
I want to add this here.

- Repository Link:- https://github.com/Susmita-Dey/Facebook-Login-Page-Clone-Tailwind-CSS
- Live demo:- https://susmita-dey.github.io/Facebook-Login-Page-Clone-Tailwind-CSS/

## **Screenshots**
![image](https://user-images.githubusercontent.com/79099734/163582996-82552ab7-b69b-4144-9667-e6a8c338915d.png)

**I'm a GSSoC'22 contributor. Kindly assign this issue to me.**

**Comment by VidhiBhatt01** [comment]
This repo is not for templates/clones
