### ISSUE TITLE
fix missing thumbnails +remove duplicate dice game

### ISSUE THREAD

**Issue by wre9-tesh** [arpit456jain/Amazing-Js-Projects#519]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- missing thumbnails for some of the tiles 
- also there are two dice game one is updated version of the previous one .

## **Possible solution**

- add preview.png to missing folders to fix this.
- remove the previous version of dice game and keep the improved version .

## **Screenshots**
![issu9e (100 × 59 4cm)](https://user-images.githubusercontent.com/96977189/163799718-2063ff1a-715d-4cfc-89a8-43e1f005f5a6.png)

![image](https://user-images.githubusercontent.com/96977189/163799836-1d54a742-a2ff-4670-8f04-7160b685b025.png)

**Comment by wre9-tesh** [comment]
i am a gssoc participant and want to work on this

**Comment by VidhiBhatt01** [comment]
I think someone else is also working on a similar issue, just check it once. If not, you can go on

**Comment by wre9-tesh** [comment]
there is a similar issue on amazing-CSS-effects repo ,but i haven't seen it here
