### ISSUE TITLE
Adding Reflex Training JS game

### ISSUE THREAD

**Issue by MonarchGitHub** [arpit456jain/Amazing-Js-Projects#525]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the feature**

- I want to add a reflex training game to the repo with minimal design. I believe that this will help beginners to learn about DOM navigation in JS and UI/UX with CSS.

- I plan to complete this project in 4 days.

**Comment by MonarchGitHub** [comment]
kindly assign this issue to me.

**Comment by VidhiBhatt01** [comment]
Keep the project size as small as possible

**Comment by MonarchGitHub** [comment]
Okay sure 👍
