### ISSUE TITLE
Haldirams Website Clone

### ISSUE THREAD

**Issue by SupriyaGembali** [arpit456jain/Amazing-Js-Projects#527]
Hii I'm a GSSoc22 contributor and I'm willing to make a pull request in this repository on my project which is Haldiram's Website Clone

The idea behind this project
This is a well Known Food Company
Please refer to the images below:
<img width="960" alt="ss1" src="https://user-images.githubusercontent.com/94470209/164533997-482c178a-6c0c-4c76-87cf-fa8532af9695.png">
<img width="960" alt="ss2" src="https://user-images.githubusercontent.com/94470209/164534027-98642cdd-a661-4a8c-9fb6-1aabd32d4c3a.png">
<img width="960" alt="ss3" src="https://user-images.githubusercontent.com/94470209/164534044-2f63d773-cf49-46e4-8b85-b29d4c342433.png">
<img width="960" alt="ss4" src="https://user-images.githubusercontent.com/94470209/164534061-206ebf62-7633-43de-bdb6-b9eee2a85b5c.png">
<img width="960" alt="ss5" src="https://user-images.githubusercontent.com/94470209/164534079-cbdbd1cb-55b4-47ec-a7ca-33352439af24.png">
<img width="960" alt="ss6" src="https://user-images.githubusercontent.com/94470209/164534096-c0c73d3c-c2bb-40ab-b622-470410e47b9a.png">

**Comment by VidhiBhatt01** [comment]
Raise this issue in Cool frontend templates repo
