### ISSUE TITLE
animated cute bear login form -by html,css,js

### ISSUE THREAD

**Issue by mayank-del** [arpit456jain/Amazing-Js-Projects#529]
## Issue Type:

It is new  feature, i want to add

## **Describe the bug**

There will will be a bear behind your form and whenever you will start typing it will  follow your cursor and when you type password it will close it's eyes

## **Possible solution**

- It will really a cool signup/login form , please assign me to contribute in this cool form under gssoc22.

## **Screenshots**

![login-form](https://user-images.githubusercontent.com/82238106/164904439-647b8224-25f7-4d08-b041-5b99869bfe45.gif)

**Comment by VidhiBhatt01** [comment]
Add a SS of the login form if possible

**Comment by mayank-del** [comment]
> Add a SS of the login form if possible

Maam , now u can  see , i have added gif.

**Comment by astha2412** [comment]
@mayank-del make PR.

**Comment by mayank-del** [comment]
Ok

**Comment by mayank-del** [comment]
When will this PR will be added in my leaderboard pr?
