### ISSUE TITLE
Add a Spotify clone having wide variety of features 

### ISSUE THREAD

**Issue by BrownCoderAyush** [arpit456jain/Amazing-Js-Projects#530]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- To add a Spotify clone having a variety of functionalities.

## **Possible solution**

- This web app will have a lot of features like.
- 1. Play, Pause, next song, previous song.
- 2. You can click on the image to play the song.
- 3. The best part is, doesn't matter how you play the song it will always go to the next song taking care of the previous one.
- 4. Also, a feature of timeupdate is given as we change the current audio time it will change the current time and also update seek bar.

## **Screenshots**

- ![Screenshot (18)](https://user-images.githubusercontent.com/86606259/164757103-d78e2e39-8cd6-45b5-a89d-5395ca9f2bdc.png).

**Comment by BrownCoderAyush** [comment]
Sir, please assign me this issue I want to work on it.

**Comment by astha2412** [comment]
@BrownCoderAyush Make PR!
