### ISSUE TITLE
Add Background color changer using HTML CSS and JavaScript

### ISSUE THREAD

**Issue by AsmaIbrahimButt** [arpit456jain/Amazing-Js-Projects#531]
## Issue Type:

- [ ] Bug Report
- [1] Feature Request
- [ ] Documentaion

## **Describe the bug**
Add a Background color changer using HTML CSS and JavaScript 
## **Possible solution**

- Describe the solution you thought of.
its a website where user can allow to change a background of a website by pressing buttons.

**Comment by AsmaIbrahimButt** [comment]
@arpit456jain Kindly assign me this issue.

**Comment by astha2412** [comment]
Yes @mayank-del Thanks!
