### ISSUE TITLE
Add Picture Puzzle Game

### ISSUE THREAD

**Issue by BabyElias** [arpit456jain/Amazing-Js-Projects#536]
I would like to add a simple drag-&-drop picture puzzle game to the repo, made using HTML,CSS & JS.
A demo is attached as below.Please assign me this issue under GSSoC.

https://user-images.githubusercontent.com/95405559/164966108-f1e6d06c-5e68-4cd7-a2ed-6aa808a1bdce.mp4

**Comment by astha2412** [comment]
Make PR @BabyElias !
