### ISSUE TITLE
Stack Game

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Amazing-Js-Projects#540]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the Project**

- Hi I'm a GSSoc22 contributor.
You have to build the towel using the square stack swinging back and forth
and score the maximum.

## **Possible solution**

- The square will move automatically
- Press space bar to stack on the top of the stack

## **Screenshots**

- 
![image](https://user-images.githubusercontent.com/72241207/165046984-97e31d0b-c55e-4a18-affd-1cb371829818.png)

**Comment by DragonUncaged** [comment]
assigned to me ?

**Comment by DragonUncaged** [comment]
@astha2412  
I see my PR was plagiarized and Invalid but my project was bit different then the link you shared.

https://codepen.io/finnhvman/pen/xJRMJp

my project was different can i try again.

https://deploy-preview-541--amazing-js-projects.netlify.app/stack_game/

**Comment by DragonUncaged** [comment]
> @DragonUncaged how did u make it ?

I Did Took Help From Online, But its Not completely Copied.

**Comment by DEEPALI-SUK** [comment]
@arpit456jain what to do?

**Comment by DragonUncaged** [comment]
> @arpit456jain what to do?

Merge the pr.
Pr is currently closed. Should i open it again
