### ISSUE TITLE
Improved Game of Tic Tac Toe

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Amazing-Js-Projects#542]
## Issue Type:

- [ ] Bug Report
- [X] Feature Request
- [ ] Documentaion

## **Describe the Project**

- A n Improved Version Of Tic Tac Toe.

## **Possible solution**

- Colorful UI
- Better Animation

## **Screenshots**

![image](https://user-images.githubusercontent.com/72241207/165063086-93568c97-44ec-4cc0-9a2f-63709944ceb9.png)

**Comment by astha2412** [comment]
Plz wait for sometime!

**Comment by DragonUncaged** [comment]
can i make changes and make PR again

**Comment by arpit456jain** [comment]
yes @DragonUncaged
