### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Amazing-Js-Projects#544]
## Issue Type:

- [ ] Bug Report
- [X] Feature Request
- [ ] Documentaion

## **Describe the Project**

- An improved Version of the Snake Game.

## **Possible solution**

- More Color.
- Better UI.

## **Screenshots**

![image](https://user-images.githubusercontent.com/72241207/165071751-d98e15d1-0aab-4a6f-a565-9c532975fe59.png)

**Comment by astha2412** [comment]
@DragonUncaged Don't make PR if u r not assigned, wait for being assigned.
