### ISSUE TITLE
Mousemove glitter effect

### ISSUE THREAD

**Issue by mayank-del** [arpit456jain/Amazing-Js-Projects#546]
## Issue Type:

- [x ] Feature Request

## **Describe the Feature**

It is javascript based mouse move effect, whenever you will move your mouse , little gliter tipe small particle will follow you.

## **Screenshots**

![mousemove](https://user-images.githubusercontent.com/82238106/165115133-acb5be0e-b288-4159-b1d7-dfca7ead1ba0.gif)

**Comment by astha2412** [comment]
@mayank-del complete all your issues then make another issue!
