### ISSUE TITLE
A Music Player

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Amazing-Js-Projects#551]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A better Optimized Music Player.

## **Possible solution**

- Better UI.

## **Screenshots**

![image](https://user-images.githubusercontent.com/72241207/165242069-abdf38c8-87a5-4b2d-9d4e-9199fc9cfc1c.png)

![image](https://user-images.githubusercontent.com/72241207/165242188-ac38a62a-15f8-4fc1-831a-69acea300a2d.png)

**Comment by VidhiBhatt01** [comment]
We already have many music players
