### ISSUE TITLE
Voice to Text Converter

### ISSUE THREAD

**Issue by Sukriti-m** [arpit456jain/Amazing-Js-Projects#554]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A Voice to Text Converter

## **Possible solution**

- I will make a Voice to Text Converter using HTML, CSS and JS.

I'd be grateful if you could assign this task to me under GSSoC22.
@arpit456jain

**Comment by VidhiBhatt01** [comment]
Please try to keep the project size as small as possible
