### ISSUE TITLE
Back to top button on homepage

### ISSUE THREAD

**Issue by jigar-sable** [arpit456jain/Amazing-Js-Projects#56]
## Issue Type:

- [x] Feature Request

## **Describe the feature**

Add scroll top button on homepage.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@jigar-sable you want to work on this or should i add label of up for grab ?

**Comment by jigar-sable** [comment]
Will work on this assign me.
