### ISSUE TITLE
Meditation Feature

### ISSUE THREAD

**Issue by shrey2003** [arpit456jain/Amazing-Js-Projects#561]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation

## **Describe the issue**
This feature allows user to meditate by selecting the required duration and required environment(forest, rain, summer night, beach) and sound effect. This project is created using HTML, CSS, JavaScript .Please assign me this issue as I am a GSSOC'22 participant.

## **Screenshots**

![image](https://user-images.githubusercontent.com/59368657/165746940-d8a1768f-80b6-46c4-a312-0faf1cac0c5b.png)

**Comment by VidhiBhatt01** [comment]
Try keeping the size as small as possible
