### ISSUE TITLE
Modify color change 

### ISSUE THREAD

**Issue by mayank-del** [arpit456jain/Amazing-Js-Projects#569]
## Issue Type:

- [ x] Bug Report
- [ x] Feature Request

## **Describe the bug**

Color are very old looking

## **Possible solution**
I can make it modern by adding awsome linear gradients instead of basic colors

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
Which project are you talking about? Kindly elaborate and add SS
