### ISSUE TITLE
some images are not rendering on home page

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#57]
## Issue Type:

- [x] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@jay-2000 you can do this if you want 
You just have to edit json file with correct path

**Comment by Atif0604** [comment]
hey @arpit456jain can i work

**Comment by arpit456jain** [comment]
Ok @Atif0604 sure but make sure you do this asap since it's urgent

**Comment by arpit456jain** [comment]
@Atif0604 any updates ?

**Comment by Atif0604** [comment]
> @Atif0604 any updates ?

yeah done
i had a merge conflict while pulling the latest changes thats why it took time


also i doubt many links were not proper so i have fixed that also and calculators doesn't have any preview so should i add it @arpit456jain

**Comment by arpit456jain** [comment]
@Atif0604 dont't worry about calculators since they will be on different page soon #46
