### ISSUE TITLE
todo app edit functionality

### ISSUE THREAD

**Issue by mayank-del** [arpit456jain/Amazing-Js-Projects#570]
## Issue Type:

- [ x] Feature Request

## **Describe the bug**

todo app is having only create and delete functionality.

## **Possible solution**

I will add one edit functionality, this will finally complete the app

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by VidhiBhatt01** [comment]
Which project are you talking about? Kindly elaborate and add SS

**Comment by arpit456jain** [comment]
> Which project are you talking about? Kindly elaborate and add SS

@mayank-del do this

**Comment by mayank-del** [comment]
![todo](https://user-images.githubusercontent.com/82238106/166144395-c1224fc5-63cc-45a8-b7cc-c38bc5462d79.png)


you can see this , user can only add and delete items, he can't edit added items, so, I  will add that functionality
