### ISSUE TITLE
pong game cpu issue

### ISSUE THREAD

**Issue by mayank-del** [arpit456jain/Amazing-Js-Projects#573]
## Issue Type:

- [ x] Bug Report
- [ x] Feature Request

## **Describe the bug**

In this game , you can check, cpu moves together with ball  it will always follow the ball and always hit it ,it will never miss it, So , in this game only PC will win. This is a  biased game currently.

## **Possible solution**
  i can make the game neutral. So that user also score good points.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by DEEPALI-SUK** [comment]
@mayank-del any updates?

**Comment by mayank-del** [comment]
Yes  sir , will surely do it by today, i am trying to understand the cpu's code, will push it as soon as possible
