### ISSUE TITLE
Text to voice

### ISSUE THREAD

**Issue by mayank-del** [arpit456jain/Amazing-Js-Projects#574]
## Issue Type:

- [ x] Feature Request

## **Describe the bug**

just like voice to text app, isn't it awesome ,if we add  text to voice project

## **Possible solution**

I want to add text to voice Project.

**Comment by VidhiBhatt01** [comment]
Add functionality in that same project

**Comment by mayank-del** [comment]
> Add functionality in that same project

Ohh, maam, i saw  few moments back , it is already present in your projects.Ok, i will surely add more functionalities in the same project.

**Comment by DEEPALI-SUK** [comment]
@mayank-del ?
