### ISSUE TITLE
Automatic Image Slider using Vanilla Js 

### ISSUE THREAD

**Issue by BrownCoderAyush** [arpit456jain/Amazing-Js-Projects#575]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- It is a beautiful image slider created using vanilla Js.

## **Possible solution**

- I have made an automatic image slider using vanilla js.
- Some of its features are :
- 1. It has multiple images working sliding itself automatically.
- 2. you can also slide from one image to another using button given below.
- 3. you can use this template in any website to get a modern style image slider.
## **Screenshots**

![Screenshot (23)](https://user-images.githubusercontent.com/86606259/165960478-53e51949-b14e-49cf-9810-71f2f48a5c2e.png)

![Screenshot (25)](https://user-images.githubusercontent.com/86606259/165960731-15c0e056-7c8b-4ffd-bc4c-e82ac54a5f08.png)

**Comment by VidhiBhatt01** [comment]
https://github.com/arpit456jain/Amazing-Js-Projects/issues/533 similar to this

Did you raise this issue anywhere else?

**Comment by BrownCoderAyush** [comment]
@VidhiBhatt01  no no this is an image slider and it is totally different form #533 . I made it on my own .
