### ISSUE TITLE
cool loading animation

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Amazing-Js-Projects#577]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A loading Animation

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/72241207/166097987-f168bd8e-f01d-43a7-b183-96be203458de.png)

**Comment by VidhiBhatt01** [comment]
Raise this issue in amazing css effects repo
