### ISSUE TITLE
Avatar Creator

### ISSUE THREAD

**Issue by DragonUncaged** [arpit456jain/Amazing-Js-Projects#578]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Avatar creator will help to customize the face color hair color dress and hair style to create the face

## **Possible solution**

- A slider to select different customization

## **Screenshots**

![image](https://user-images.githubusercontent.com/72241207/166101212-50395bf8-9e47-494c-a0c9-ec826a061a79.png)

**Comment by VidhiBhatt01** [comment]
in cool frontend templates repo
