### ISSUE TITLE
Music library  using API

### ISSUE THREAD

**Issue by yash-25log** [arpit456jain/Amazing-Js-Projects#581]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the Feature**

A music library system to get lyrics of any song 
work on fetching results from api

gave a unique ui like spotify or better

API used - https://api.lyrics.ovh

Will make responsive soon

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/58944204/166117535-3c4a71a2-e355-48df-9383-14ffb10d596e.png)
![image](https://user-images.githubusercontent.com/58944204/166117553-d44c1706-cc8b-4478-be33-2a78b2262433.png)

**Comment by VidhiBhatt01** [comment]
We already have music player

**Comment by yash-25log** [comment]
> We already have music player

it's not music player
it fetches lyrics from api with search
