### ISSUE TITLE
The Simon Game

### ISSUE THREAD

**Issue by ravencode69** [arpit456jain/Amazing-Js-Projects#589]
## Issue Type:

- [ ] Bug Report
- [ x] Feature Request
- [ ] Documentaion

A memory inducing fun game using vanilla JS, CSS and HTML

## **Screenshots**
![simon](https://user-images.githubusercontent.com/86804513/166159405-1040273a-006f-491a-8e0e-8e7b9c61d16a.png)

**Comment by DEEPALI-SUK** [comment]
@ravencode69 this is already present in the repo

**Comment by ravencode69** [comment]
oops my bad I'll close it
