### ISSUE TITLE
Age Calculator presentation issue

### ISSUE THREAD

**Issue by Qamberhasnain** [arpit456jain/Amazing-Js-Projects#591]
## Issue Type:

- [X] Bug Report
- [X] Feature Request

## **Describe the bug**

- After thorough reading and analyzing of [index.html](https://github.com/arpit456jain/Amazing-Js-Projects/blob/master/Age%20Calculator/index.html). I found that it has an error which was causing difficulties in its deployment and that error was because of closing div tag wasn't there.
- As it can be seen in the screenshot that it shows only numbers after calculation in the boxes of *Years*, *Months* and *Days*. It seems odd that only numbers are written their without any unit.
- For the output font size and color is oddly white and big and it doesn't match the font size and color before output.

## **Possible solution**

- Put a **Underscore** or **Hyphen** to represent null at the starting and then put those number in the place of **Underscore** or **Hyphen** instead of *Years*, *Months* and *Days*.

## **Screenshots**

![image](https://user-images.githubusercontent.com/63412921/166221738-052546c8-52fe-47da-8ad5-7d7b175e5fd8.png)

![image](https://user-images.githubusercontent.com/63412921/166221577-313539a2-a483-47d2-ae08-3d1efb500aba.png)

**Comment by DEEPALI-SUK** [comment]
@Qamberhasnain this is already present

**Comment by VidhiBhatt01** [comment]
You can raise the PR now. Add all the changes in 1 PR only

**Comment by Qamberhasnain** [comment]
> You can raise the PR now. Add all the changes in 1 PR only

Can you please help me about this. I don't know how to add all the changes to one file.
