### ISSUE TITLE
Calculator 4

### ISSUE THREAD

**Issue by kiruba-r11** [arpit456jain/Amazing-Js-Projects#6]
I would like to add a Calculator with the following features:
  1. Both Light and Dark Mode.
  2. For every wrong input, there is an alert thrown, so calculator works error-free for all edge cases.
  3. It is completely `Responsive`.

Screenshots:
<table>
  <thead>
    <th>Dark Mode</th>
    <th>Light Mode</th>
  </thead>
  <tbody>
    <tr>
      <td><img width="500" src="https://user-images.githubusercontent.com/76843281/124748595-f10d1700-df40-11eb-8d0d-6a134e37e3b0.png"></td>
       <td><img width="500" src="https://user-images.githubusercontent.com/76843281/124748597-f23e4400-df40-11eb-8041-f72c286f2ae3.png"></td>
    </tr>
  </tbody>
</table>

**Comment by kiruba-r11** [comment]
@arpit456jain I would like to work on this.

**Comment by kiruba-r11** [comment]
@arpit456jain can I work on this?

**Comment by arpit456jain** [comment]
@kiruba-r11 yes you can work on this but please make PR after 15 July since this repo is being used in an event 
**Wield The Web**  
or
you can particpate in this event and  make PR .
For more information please join our CES Community 
https://discord.gg/FVPvDUXfRR

**Comment by arpit456jain** [comment]
@kiruba-r11 you can make the PR

**Comment by kiruba-r11** [comment]
@arpit456jain Can i work on this as a part of DCP'21?

**Comment by arpit456jain** [comment]
Yes ofcourse @kiruba-r11
