### ISSUE TITLE
Special Number Checker

### ISSUE THREAD

**Issue by eswarbhageerath** [arpit456jain/Amazing-Js-Projects#600]
A number is said to be a special number when the sum of the factorial of its digits is equal to the number itself.
Example: 145 is a Special Number as 1!+4!+5!=145.

Enter any number and know whether it is a special number or not.

**Comment by VidhiBhatt01** [comment]
I think we have a similar project in this repo, please verify once. If not then you can go on

**Comment by eswarbhageerath** [comment]
After verifying, I am proceeding with my PR mam. Thank you.
