### ISSUE TITLE
Add some more JS projects

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#61]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

Add some new projects just create a new issue describe about your ideas and start working on it

**Comment by Atif0604** [comment]
Hey @arpit456jain  i want to add movie search app using api 
so should make a new issue or it will be assigned in this issue

**Comment by arpit456jain** [comment]
@Atif0604 make a new issue

**Comment by Skapsime** [comment]
could you please assign me on this issue i will be adding some more js project

**Comment by arpit456jain** [comment]
@Skapsime make a new issue for a new project (separate issue for different  project)

**Comment by Skapsime** [comment]
> @Skapsime make a new issue for a new project (separate issue for different project)

okay
