### ISSUE TITLE
Random Password Generator

### ISSUE THREAD

**Issue by Aayush987** [arpit456jain/Amazing-Js-Projects#613]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A random password generator that generates up to 4 random passwords of length 6 just by clicking generate button.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![rpwdgenerator](https://user-images.githubusercontent.com/92387745/166640381-8ff3ec70-b397-40ac-86bd-4563f5937d8e.png)

**Comment by DEEPALI-SUK** [comment]
@Aayush987 this project is already present

**Comment by Aayush987** [comment]
> If u can add some extra features then do this else close this issue

Its different from that password generator ,here in just click of a single button we can generate 4 random password at once. At with just one click we can copy it and use it.
