### ISSUE TITLE
Improve Read me

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#63]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Dhruv-194** [comment]
@arpit456jain What exactly do you want add and update in the readme? Are their any specific contents which you would like to add in it?

**Comment by arpit456jain** [comment]
well @Dhruv-194  there is no such specifications if you have an idea to make it better you can try like

1. badges of html ,css ,js instead of text 

anything you have on your mind

**Comment by Dhruv-194** [comment]
> well @Dhruv-194 there is no such specifications if you have an idea to make it better you can try like
> 
> 1. badges of html ,css ,js instead of text
> 
> anything you have on your mind

okay @arpit456jain I will add those badges and try to modify the README file as much as I can. Kindly please assign me this issue.

**Comment by arpit456jain** [comment]
go ahead @Dhruv-194

**Comment by arpit456jain** [comment]
@Dhruv-194 ?

**Comment by Dhruv-194** [comment]
@arpit456jain kindly check my linked PR with this issue!
