### ISSUE TITLE
Movie Search App

### ISSUE THREAD

**Issue by Atif0604** [arpit456jain/Amazing-Js-Projects#64]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Add Movie Search App using Api

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Atif0604** [comment]
Hey @arpit456jain Please assign this issue

**Comment by arpit456jain** [comment]
go ahead @Atif0604

**Comment by ankitapuri** [comment]
@Atif0604 your deadline is 1st Aug
