### ISSUE TITLE
Jump D Block: game

### ISSUE THREAD

**Issue by BIKRAM-SAHA** [arpit456jain/Amazing-Js-Projects#641]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A game developed using JS where the user jumps over blocks
- Works on mobile too

## **Screenshots**
[![game1.png](https://i.postimg.cc/nzyjLfM0/game1.png)](https://postimg.cc/bDRN6Mxt)
[![game2.png](https://i.postimg.cc/jSxW2Xd0/game2.png)](https://postimg.cc/w7rxbDm0)

**Comment by DEEPALI-SUK** [comment]
This game is already there ig

**Comment by DEEPALI-SUK** [comment]
T-Rex runner game is somewhat similar to this
