### ISSUE TITLE
Burger menu

### ISSUE THREAD

**Issue by void-ness** [arpit456jain/Amazing-Js-Projects#656]
## Issue Type:
- [ ] Feature Request

## implement a hardcoded burger menu.

- on the desktop version a navbar with different nav icons will come. whereas on phone, nav icons will collapse and be replaced by a burger icon/ bars, clicking on which, will then toggle a menu with nav icons.

**Comment by void-ness** [comment]
kindly assign the task to me, I would love to work on it

**Comment by void-ness** [comment]
thank you for assigning it. i will get back to you with the assigned work soon

**Comment by arpit456jain** [comment]
@void-ness

**Comment by void-ness** [comment]
Thank You so much for giving me an opportunity to contribute. I have added my contribution towards the above through the following pull request (#684). I would request you to kindly review it and merge it. I am GSSoC contributor and would appreciate if you can assign a level tag to my contribution too. Thank you
