### ISSUE TITLE
Random Choice Picker

### ISSUE THREAD

**Issue by Khushi-Mattu** [arpit456jain/Amazing-Js-Projects#658]
## Issue Type:

- [ ] Bug Report
- [* ] Feature Request
- [ ] Documentaion

To add a random choice picker where in you add options or various choice and it picks up a random one from them
## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by DEEPALI-SUK** [comment]
@Khushi-Mattu add a small demo video
