### ISSUE TITLE
Water Counter

### ISSUE THREAD

**Issue by Khushi-Mattu** [arpit456jain/Amazing-Js-Projects#659]
## Issue Type:

- [ ] Bug Report
- [*] Feature Request
- [ ] Documentaion

## **Describe the bug**

A counter which increments the water level according to the amount of water you keep drinking. It will help you keep a check on your water intake.

## **Possible solution**
A counter which increments the water level according to the amount of water you keep drinking.

## **Screenshots**

![image](https://user-images.githubusercontent.com/82451914/168106577-1c9411cb-fb3d-46b7-9118-5c14563c2c6a.png)

**Comment by arpit456jain** [comment]
@Khushi-Mattu
