### ISSUE TITLE
Custom Range Slider

### ISSUE THREAD

**Issue by Atif0604** [arpit456jain/Amazing-Js-Projects#66]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Add Custom Range Slider

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by ankitapuri** [comment]
Go ahead @Atif0604
