### ISSUE TITLE
Random Image Feed

### ISSUE THREAD

**Issue by Khushi-Mattu** [arpit456jain/Amazing-Js-Projects#662]
## Issue Type:

- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

A webpage is loaded with random images and there are new images everytime you reload the page.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/82451914/168223849-409298bd-ea78-46a7-b82f-726a893d0950.png)

After refreshing
![image](https://user-images.githubusercontent.com/82451914/168223775-c73a07bc-83f1-4b09-8e9d-1ac0114e9132.png)

**Comment by arpit456jain** [comment]
@Khushi-Mattu
