### ISSUE TITLE
A: Revamp/Change the entire UI of Special Number Checker

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Amazing-Js-Projects#664]
![image](https://user-images.githubusercontent.com/83345228/168294844-d64d145a-886a-412e-a385-36577160f730.png)

**Comment by BIKRAM-SAHA** [comment]
@VidhiBhatt01 Hi, I would love to volunteer for this issue. What kind of UI do you want this project to have? Do you have some designs or anything for reference?

**Comment by aachal28** [comment]
I would like to pick up this issue under GSSOC'22. Midway through it. Kindly assign it to me.

**Comment by DEEPALI-SUK** [comment]
> @VidhiBhatt01 Hi, I would love to volunteer for this issue. What kind of UI do you want this project to have? Do you have some designs or anything for reference?

change it as u want and make it attractive
