### ISSUE TITLE
B: Enhance the UI of Analog Clock

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Amazing-Js-Projects#665]
![image](https://user-images.githubusercontent.com/83345228/168295222-e5eeb739-2de8-4ee1-9288-6dd5c0b54b02.png)
![image](https://user-images.githubusercontent.com/83345228/168295254-4dc7698b-450f-4152-aeff-8aeb6117ae2c.png)

**Comment by BIKRAM-SAHA** [comment]
Hi @VidhiBhatt01 I Would love to work on this issue. Do you have any prior design suggestions or goals that you want to be implemented?

**Comment by BIKRAM-SAHA** [comment]
@VidhiBhatt01 Does this look good?


![image](https://user-images.githubusercontent.com/74536497/168763357-01fc9107-8ef3-40db-9d43-880b249691b2.png)
![image](https://user-images.githubusercontent.com/74536497/168763544-b75d5884-5a86-411b-9e6e-1ba243e61652.png)

**Comment by arpit456jain** [comment]
@BIKRAM-SAHA  go ahead

**Comment by BIKRAM-SAHA** [comment]
@arpit456jain @VidhiBhatt01 
I suggest to remove this element which appears on hovering over the clock

![image](https://user-images.githubusercontent.com/74536497/168881172-87221119-22db-45d4-9453-0ce6f13b338d.png)

as shown in the following video

https://vimeo.com/710908942

I dont think there is any specific use for this element and it just clutters the UI. What do you advice should I remove it or let it be?

**Comment by VidhiBhatt01** [comment]
Fit it somewhere by using some CSS. Don't remove it
