### ISSUE TITLE
E: Beautify clock and alarm and increase the font sizing 

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Amazing-Js-Projects#668]
![image](https://user-images.githubusercontent.com/83345228/168296369-66038e21-ec97-4061-bc6d-d5acf66bf065.png)

**Comment by BIKRAM-SAHA** [comment]
Hi @VidhiBhatt01 would like to volunteer to do the specified changes.

**Comment by VidhiBhatt01** [comment]
any updates?

**Comment by BIKRAM-SAHA** [comment]
> any updates?

@VidhiBhatt01 
Just finished working on it. Do mention if any further changes are to be done!
