### ISSUE TITLE
H: Improve the UI of quote generator

### ISSUE THREAD

**Issue by VidhiBhatt01** [arpit456jain/Amazing-Js-Projects#671]
![image](https://user-images.githubusercontent.com/83345228/168297580-2b95ca9c-68c7-4a0e-8a6a-6696c3545dbd.png)

**Comment by BabyElias** [comment]
I would like to take up this issue.Please assign me.

**Comment by AmolShelke2** [comment]
Hey @VidhiBhatt01 I would love to make this nice can you assign me.

**Comment by VidhiBhatt01** [comment]
Fcfs basis, you can check out other issues
