### ISSUE TITLE
Word Count Tool

### ISSUE THREAD

**Issue by BIKRAM-SAHA** [arpit456jain/Amazing-Js-Projects#674]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Possible solution**

- This project counts the no of words, sentences and paragraphs in the text pasted in the textarea
- It is mobile responsive

## **Screenshots**

![image](https://user-images.githubusercontent.com/74536497/168442436-b47e9a80-ec4e-48c4-908b-39df405364bf.png)

![image](https://user-images.githubusercontent.com/74536497/168442470-2d5b48a6-1d50-41b4-8832-38f0baa797bd.png)

**Comment by BIKRAM-SAHA** [comment]
@arpit456jain @VidhiBhatt01 May someone please assign me the issue.

**Comment by VidhiBhatt01** [comment]
Please don't keep it plain, add some colors :)

**Comment by sb0603** [comment]
I am gssoc contributer ,can u please assign this issue to me.

**Comment by BIKRAM-SAHA** [comment]
> I am gssoc contributer ,can u please assign this issue to me.

Hi, am currently working on this issue. :)
