### ISSUE TITLE
Alien Invader Game

### ISSUE THREAD

**Issue by AnIkeT126** [arpit456jain/Amazing-Js-Projects#681]
## Issue Type:

- [x] Feature Request

## **Describe the bug**

- A web app based alien invader game, that has alien dominos moving rapidly and we have to hit them to gain points. c

## **Possible solution**

- A simple js based solution that will be  fully responsive.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by DEEPALI-SUK** [comment]
@AnIkeT126 add a demo video

**Comment by AnIkeT126** [comment]
> @AnIkeT126 add a demo video

Can I add that with PR

**Comment by VidhiBhatt01** [comment]
We need to see what you want to add before assigning, so it would be great if you can add here
