### ISSUE TITLE
Make a slider component responsive Enhancement.

### ISSUE THREAD

**Issue by AmolShelke2** [arpit456jain/Amazing-Js-Projects#682]
## Issue Type:

- [x] Bug Report

## **Describe the bug**

- If there is anyone who can make my slider project responsive it will be very good if someone can work on this issue if anyone wants to work on this issue just comment down below.

## **Possible solution**

- Make it responsive for mobile devices.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

![168652160-858006be-794f-4ba4-9608-f88a8b8e8df3](https://user-images.githubusercontent.com/95171638/168837729-3ac58d26-297d-4e71-b8f4-95ffa7dfc52e.png)

**Comment by Anirban-1490** [comment]
@VidhiBhatt01 give me this,  and which project is this ?

**Comment by DEEPALI-SUK** [comment]
@AmolShelke2 which project is this?

**Comment by AmolShelke2** [comment]
> @AmolShelke2 which project is this?

[Feedback slider](https://github.com/arpit456jain/Amazing-Js-Projects/tree/master/Feedback%20slider)

**Comment by Anirban-1490** [comment]
> > @AmolShelke2 which project is this?
> 
> @DEEPALI-SUK , @Anirban-1490 [Feedback slider](https://github.com/arpit456jain/Amazing-Js-Projects/tree/master/Feedback%20slider)

ok got it

**Comment by AmolShelke2** [comment]
It is a feedback slider project
