### ISSUE TITLE
Get Quote of the day by click on the button

### ISSUE THREAD

**Issue by nik132-eng** [arpit456jain/Amazing-Js-Projects#687]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**
My simple project gives a quote when the user clicks on the button.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**
![image](https://user-images.githubusercontent.com/77881638/169510751-69acefce-bb7a-4dc8-8bb7-f25c0cb3d61b.png)

![image](https://user-images.githubusercontent.com/77881638/169510788-a9566895-fdb7-4905-afb0-5cad8dac0944.png)

Please assign me this issue so I can add the project to your repository.

**Comment by VidhiBhatt01** [comment]
This project is also already present in the repo
