### ISSUE TITLE
Analog Clock

### ISSUE THREAD

**Issue by nik132-eng** [arpit456jain/Amazing-Js-Projects#688]
## Issue Type:

- [ ] Bug Report
- [X] Feature Request
- [ ] Documentaion

## **Describe the bug**
My simple project with HTML, CSS & JS

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

![image](https://user-images.githubusercontent.com/77881638/169511617-efe80982-7124-45ce-b1cc-92634ed3f0d4.png)

- If applicable, add screenshots to help explain your problem.

**Comment by nik132-eng** [comment]
please assign me this issue so I can add it to your repository.

thank you

**Comment by VidhiBhatt01** [comment]
We already have many clocks
