### ISSUE TITLE
MoneyTransferApplication

### ISSUE THREAD

**Issue by SamarthKadam** [arpit456jain/Amazing-Js-Projects#697]
Can I add this Bankist Web application where users can transfer money, and take loans like features implemented. This project is
built using javascript  html css . This project was build under the guidance of instructor
You can have a look below
![Screenshot (199)](https://user-images.githubusercontent.com/87573175/169678394-35ef5058-5a09-430c-be0c-7339041846b5.png)

**Comment by SamarthKadam** [comment]
Can I add this?

**Comment by DEEPALI-SUK** [comment]
@SamarthKadam complete within 3 days

**Comment by DEEPALI-SUK** [comment]
@SamarthKadam any updates?

**Comment by SamarthKadam** [comment]
Yes ill do it by today
