### ISSUE TITLE
Snake Game

### ISSUE THREAD

**Issue by Atif0604** [arpit456jain/Amazing-Js-Projects#70]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A Snake Game for desktop
## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by arpit456jain** [comment]
@Atif0604 go ahead
