### ISSUE TITLE
add remaining projects in json file

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#71]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Atif0604** [comment]
can i work @arpit456jain

**Comment by arpit456jain** [comment]
@Atif0604 go ahead and don't forget to add screenshots in respective folder if its not present name it as preview.png
