### ISSUE TITLE
Game of Tetris

### ISSUE THREAD

**Issue by hariketsheth** [arpit456jain/Amazing-Js-Projects#710]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**
- Would like to add JS Project for implementing Game of Tetris

**Comment by hariketsheth** [comment]
@DEEPALI-SUK Assign me this issue

**Comment by DEEPALI-SUK** [comment]
@hariketsheth sorry now no new issues will be assigned
