### ISSUE TITLE
Draggable Navigation bar

### ISSUE THREAD

**Issue by dheerajrao20** [arpit456jain/Amazing-Js-Projects#716]
In modern web dev we need some modern things and obviously crazy too. So I want to add a draggable navbar into the project.
You can drag it throughout your webpages and open the navbar like a box.
I had made this sometimes before and have the source code right now.
Kindly assign this issue to me so that I can add it as soon as possible

@arpit456jain  Kindly assign this issue to me.

**Comment by DEEPALI-SUK** [comment]
@dheerajrao20 sorry now we are not assigning any issues, thanks for your time!
