### ISSUE TITLE
SORT REPO ALPHABETICALLY AND MAKE EVERYTHING WORKING

### ISSUE THREAD

**Issue by Abh1shekSingh** [arpit456jain/Amazing-Js-Projects#717]
## Issue Type:

- [x] Bug Report
- [x] Feature Request
- [x] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Abh1shekSingh** [comment]
@VidhiBhatt01 @DEEPIKA-SUK @astha2412 Please Assign the task

**Comment by arpit456jain** [comment]
@Abh1shekSingh
