### ISSUE TITLE
Delete the plag projects 

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#718]
https://docs.google.com/spreadsheets/d/1Z1fdg77locdd5OjCIlUwwjMWh7jqD5hVG2S5HhbByVE/edit?usp=sharing

this is the list of Plag PRs open link one by one and find the folder name of project which they are adding and delete that folder

**Comment by prabhkaur301** [comment]
I will do this

**Comment by arpit456jain** [comment]
ok @prabhkaur301
