### ISSUE TITLE
add a gif of home page in read me

### ISSUE THREAD

**Issue by arpit456jain** [arpit456jain/Amazing-Js-Projects#78]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

add a gif in read me like this repo
https://github.com/arpit456jain/Cool-Front-End_Templates

**Comment by Dhruv-194** [comment]
Hey @arpit456jain can I work on this issue?

**Comment by arpit456jain** [comment]
yes @Dhruv-194

**Comment by arpit456jain** [comment]
@Dhruv-194 any updates?

**Comment by Dhruv-194** [comment]
@arpit456jain thanks for reminding I will do it by today itself :)
