### ISSUE TITLE
 Rocket Web Animation

### ISSUE THREAD

**Issue by Skapsime** [arpit456jain/Amazing-Js-Projects#79]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Skapsime** [comment]
Please Assign me.

**Comment by arpit456jain** [comment]
Go ahead @Skapsime

**Comment by Skapsime** [comment]
> Go ahead @Skapsime

okay Thanks
