### ISSUE TITLE
Comet Effects

### ISSUE THREAD

**Issue by Skapsime** [arpit456jain/Amazing-Js-Projects#82]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Skapsime** [comment]
please assign me

**Comment by arpit456jain** [comment]
@Skapsime create this issue on Css effects this repo is for js projects

**Comment by Skapsime** [comment]
okay
