### ISSUE TITLE
StopWatch

### ISSUE THREAD

**Issue by Skapsime** [arpit456jain/Amazing-Js-Projects#85]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Skapsime** [comment]
please assign me asap

**Comment by Skapsime** [comment]
I have already done my work

**Comment by arpit456jain** [comment]
ok @Skapsime
