### ISSUE TITLE
Double Vertical Slider

### ISSUE THREAD

**Issue by Atif0604** [arpit456jain/Amazing-Js-Projects#88]
## Issue Type:

- [ ] Bug Report
- [x] Feature Request
- [ ] Documentaion

## **Describe the bug**

- Add Double Vertical Slider for desktop

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Atif0604** [comment]
hey @arpit456jain 
please assign

**Comment by arpit456jain** [comment]
go ahead @Atif0604
