### ISSUE TITLE
Breakout Game

### ISSUE THREAD

**Issue by Skapsime** [arpit456jain/Amazing-Js-Projects#89]
## Issue Type:

- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentaion

## **Describe the bug**

- A clear and concise description of what the bug is.

## **Possible solution**

- Describe the solution you thought of.

## **Screenshots**

- If applicable, add screenshots to help explain your problem.

**Comment by Skapsime** [comment]
please assign  me i have already done my work

**Comment by arpit456jain** [comment]
go ahead @Skapsime 

hey @Skapsime since only 3 days left and you have many issue to work so don't  wait for assignment just make PR asap

**Comment by Skapsime** [comment]
okay
