### ISSUE TITLE
New project upcoming today - CSS Minifier with cool UI/UX

### ISSUE THREAD

**Issue by vaibhavHere** [arpit456jain/Amazing-Js-Projects#96]
New project upcoming tonight.
Tech stack: HTML/ CSS/ JS

**Comment by arpit456jain** [comment]
go ahead @vaibhavHere 

by the way are you sure its js project ? if not then please create this issue and  make PR on  https://github.com/arpit456jain/Amazing-Css-Effects  don't wait for assigning
